MLIR: mlir::edsc::LoopNestBuilder Class Reference
mlir::edsc::LoopNestBuilder Class Reference
Helper class to sugar building scf.for loop nests from ranges.
#include "mlir/Dialect/SCF/EDSC/Builders.h"
Public Member Functions
LoopNestBuilder (Value *iv, Value lb, Value ub, Value step)
LoopNestBuilder (Value *iv, Value lb, Value ub, Value step, MutableArrayRef< Value > iterArgsHandles, ValueRange iterArgsInitValues)
LoopNestBuilder (MutableArrayRef< Value > ivs, ArrayRef< Value > lbs, ArrayRef< Value > ubs, ArrayRef< Value > steps)
ValueRange operator() (std::function< void(void)> fun=nullptr)
Detailed Description
Helper class to sugar building scf.for loop nests from ranges.
This is similar to edsc::AffineLoopNestBuilder except it operates on scf.for.
Definition at line 60 of file Builders.h.
Constructor & Destructor Documentation
LoopNestBuilder() [1/3]
mlir::edsc::LoopNestBuilder::LoopNestBuilder (Value * iv, Value lb, Value ub, Value step)
Definition at line 64 of file Builders.cpp.
References mlir::edsc::makeLoopBuilder().
LoopNestBuilder() [2/3]
mlir::edsc::LoopNestBuilder::LoopNestBuilder (Value * iv, Value lb, Value ub, Value step, MutableArrayRef< Value > iterArgsHandles, ValueRange iterArgsInitValues)
Definition at line 55 of file Builders.cpp.
References mlir::edsc::makeLoopBuilder().
LoopNestBuilder() [3/3]
mlir::edsc::LoopNestBuilder::LoopNestBuilder (MutableArrayRef< Value > ivs, ArrayRef< Value > lbs, ArrayRef< Value > ubs, ArrayRef< Value > steps)
Definition at line 40 of file Builders.cpp.
References mlir::edsc::makeLoopBuilder().
Member Function Documentation
operator()()
ValueRange mlir::edsc::LoopNestBuilder::operator() (std::function< void(void)> fun = nullptr)
The documentation for this class was generated from the following files:
include/mlir/Dialect/SCF/EDSC/Builders.h
lib/Dialect/SCF/EDSC/Builders.cpp