MLIR: mlir::spirv::CooperativeMatrixNVType Class Reference
mlir::spirv::CooperativeMatrixNVType Class Reference
#include "mlir/Dialect/SPIRV/SPIRVTypes.h"
Public Member Functions
Type getElementType () const
spirv::Scope getScope () const
Return the scope of the cooperative matrix.
unsigned getRows () const
return the number of rows of the matrix.
unsigned getColumns () const
return the number of columns of the matrix.
void getExtensions (SPIRVType::ExtensionArrayRefVector &extensions, Optional< spirv::StorageClass > storage=llvm::None)
void getCapabilities (SPIRVType::CapabilityArrayRefVector &capabilities, Optional< spirv::StorageClass > storage=llvm::None)
Static Public Member Functions
static bool kindof (unsigned kind)
static CooperativeMatrixNVType get (Type elementType, spirv::Scope scope, unsigned rows, unsigned columns)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 369 of file SPIRVTypes.h.
Member Function Documentation
get()
CooperativeMatrixNVType CooperativeMatrixNVType::get (Type elementType, spirv::Scope scope, unsigned rows, unsigned columns) static
Definition at line 313 of file SPIRVTypes.cpp.
References mlir::spirv::TypeKind::CooperativeMatrix, and mlir::Type::getContext().
Referenced by isFnEntryBlock(), and parseCooperativeMatrixType().
getCapabilities()
void CooperativeMatrixNVType::getCapabilities (SPIRVType::CapabilityArrayRefVector & capabilities, Optional< spirv::StorageClass > storage = llvm::None)
Definition at line 343 of file SPIRVTypes.cpp.
References mlir::Type::cast(), and getElementType().
getColumns()
unsigned CooperativeMatrixNVType::getColumns () const
return the number of columns of the matrix.
Definition at line 330 of file SPIRVTypes.cpp.
Referenced by print().
getElementType()
Type CooperativeMatrixNVType::getElementType () const
Definition at line 320 of file SPIRVTypes.cpp.
Referenced by print().
getExtensions()
void CooperativeMatrixNVType::getExtensions (SPIRVType::ExtensionArrayRefVector & extensions, Optional< spirv::StorageClass > storage = llvm::None)
Definition at line 334 of file SPIRVTypes.cpp.
References mlir::Type::cast(), and getElementType().
getRows()
unsigned CooperativeMatrixNVType::getRows () const
return the number of rows of the matrix.
Definition at line 328 of file SPIRVTypes.cpp.
Referenced by print().
getScope()
Scope CooperativeMatrixNVType::getScope () const
Return the scope of the cooperative matrix.
Definition at line 324 of file SPIRVTypes.cpp.
Referenced by print().
kindof()
static bool mlir::spirv::CooperativeMatrixNVType::kindof (unsigned kind) inline static
Definition at line 375 of file SPIRVTypes.h.
References mlir::spirv::TypeKind::CooperativeMatrix, getElementType(), and mlir::StandardTypes::None.
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/SPIRVTypes.h
lib/Dialect/SPIRV/SPIRVTypes.cpp