MLIR: mlir::edsc::TemplatedIndexedValue< Load, Store > Class Template Reference
mlir::edsc::TemplatedIndexedValue< Load, Store > Class Template Reference
A TemplatedIndexedValue brings an index notation over the template Load and Store parameters.
#include "mlir/EDSC/Builders.h"
Public Member Functions
TemplatedIndexedValue (Value v)
TemplatedIndexedValue (const TemplatedIndexedValue &rhs)=default
TemplatedIndexedValue operator() ()
TemplatedIndexedValue operator() (Value index)
Returns a new TemplatedIndexedValue.
template<typename... Args>
TemplatedIndexedValue operator() (Value index, Args... indices)
TemplatedIndexedValue operator() (ArrayRef< Value > indices)
Store operator= (const TemplatedIndexedValue &rhs)
Emits a store.
Store operator= (Value rhs)
operator Value () const
Emits a load when converting to a Value.
Value getBase () const
Returns the base memref.
MemRefType getMemRefType () const
Returns the underlying memref.
template<typename T >
T getElementalTypeAs () const
Returns the underlying MemRef elemental type cast as T.
Value operator+ (Value e)
Arithmetic operator overloadings.
Value operator- (Value e)
Value operator* (Value e)
Value operator/ (Value e)
Value operator% (Value e)
Value operator^ (Value e)
Value operator+ (TemplatedIndexedValue e)
Value operator- (TemplatedIndexedValue e)
Value operator* (TemplatedIndexedValue e)
Value operator/ (TemplatedIndexedValue e)
Value operator% (TemplatedIndexedValue e)
Value operator^ (TemplatedIndexedValue e)
Store operator+= (Value e)
Assignment-arithmetic operator overloadings.
Store operator-= (Value e)
Store operator*= (Value e)
Store operator/= (Value e)
Store operator%= (Value e)
Store operator^= (Value e)
Store operator+= (TemplatedIndexedValue e)
Store operator-= (TemplatedIndexedValue e)
Store operator*= (TemplatedIndexedValue e)
Store operator/= (TemplatedIndexedValue e)
Store operator%= (TemplatedIndexedValue e)
Store operator^= (TemplatedIndexedValue e)
Value operator && (Value e)
Logical operator overloadings.
Value operator|| (Value e)
Value operator && (TemplatedIndexedValue e)
Value operator|| (TemplatedIndexedValue e)
Value eq (Value e)
Comparison operator overloadings.
Value ne (Value e)
Value operator< (Value e)
Value operator<= (Value e)
Value operator> (Value e)
Value operator>= (Value e)
Value operator< (TemplatedIndexedValue e)
Value operator<= (TemplatedIndexedValue e)
Value operator> (TemplatedIndexedValue e)
Value operator>= (TemplatedIndexedValue e)
Detailed Description
template<typename Load, typename Store>
class mlir::edsc::TemplatedIndexedValue< Load, Store >
A TemplatedIndexedValue brings an index notation over the template Load and Store parameters.
Assigning to an IndexedValue emits an actual Store operation, while converting an IndexedValue to a Value emits an actual Load operation.
Definition at line 331 of file Builders.h.
Constructor & Destructor Documentation
TemplatedIndexedValue() [1/2]
template<typename Load , typename Store > mlir::edsc::TemplatedIndexedValue< Load, Store >::TemplatedIndexedValue (Value v) inline explicit
Definition at line 333 of file Builders.h.
TemplatedIndexedValue() [2/2]
template<typename Load , typename Store > mlir::edsc::TemplatedIndexedValue< Load, Store >::TemplatedIndexedValue (const TemplatedIndexedValue< Load, Store > & rhs) default
Member Function Documentation
eq()
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::eq (Value e)
Comparison operator overloadings.
Definition at line 201 of file Builders.h.
References mlir::edsc::op::eq().
getBase()
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::getBase () const inline
Returns the base memref.
Definition at line 362 of file Builders.h.
getElementalTypeAs()
template<typename Load , typename Store > template<typename T > T mlir::edsc::TemplatedIndexedValue< Load, Store >::getElementalTypeAs () const inline
Returns the underlying MemRef elemental type cast as T.
Definition at line 371 of file Builders.h.
References getElementType(), mlir::edsc::op::operator%(), mlir::operator*(), mlir::operator+(), mlir::operator-(), mlir::edsc::op::operator/(), and mlir::edsc::op::operator^().
getMemRefType()
template<typename Load , typename Store > MemRefType mlir::edsc::TemplatedIndexedValue< Load, Store >::getMemRefType () const inline
Returns the underlying memref.
Definition at line 365 of file Builders.h.
ne()
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::ne (Value e)
Definition at line 205 of file Builders.h.
References mlir::edsc::op::ne().
operator &&() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator&& (Value e)
Logical operator overloadings.
Referenced by mlir::edsc::TemplatedIndexedValue< Load, Store >::operator^=().
operator &&() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator&& (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 433 of file Builders.h.
operator Value()
template<typename Load , typename Store > mlir::edsc::TemplatedIndexedValue< Load, Store >::operator Value () const inline
Emits a load when converting to a Value.
Definition at line 359 of file Builders.h.
operator%() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator% (Value e)
Definition at line 145 of file Builders.h.
operator%() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator% (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 397 of file Builders.h.
operator%=() [1/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator%= (Value e)
Definition at line 177 of file Builders.h.
operator%=() [2/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator%= (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 423 of file Builders.h.
operator()() [1/4]
template<typename Load , typename Store > TemplatedIndexedValue mlir::edsc::TemplatedIndexedValue< Load, Store >::operator() () inline
Definition at line 337 of file Builders.h.
operator()() [2/4]
template<typename Load , typename Store > TemplatedIndexedValue mlir::edsc::TemplatedIndexedValue< Load, Store >::operator() (Value index) inline
Returns a new TemplatedIndexedValue.
Definition at line 339 of file Builders.h.
operator()() [3/4]
template<typename Load , typename Store > template<typename... Args> TemplatedIndexedValue mlir::edsc::TemplatedIndexedValue< Load, Store >::operator() (Value index, Args... indices) inline
Definition at line 345 of file Builders.h.
operator()() [4/4]
template<typename Load , typename Store > TemplatedIndexedValue mlir::edsc::TemplatedIndexedValue< Load, Store >::operator() (ArrayRef< Value > indices) inline
Definition at line 348 of file Builders.h.
operator*() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator* (Value e)
Definition at line 135 of file Builders.h.
operator*() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator* (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 391 of file Builders.h.
operator*=() [1/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator*= (Value e)
Definition at line 167 of file Builders.h.
operator*=() [2/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator*= (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 417 of file Builders.h.
operator+() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator+ (Value e)
Arithmetic operator overloadings.
Definition at line 125 of file Builders.h.
operator+() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator+ (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 385 of file Builders.h.
operator+=() [1/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator+= (Value e)
Assignment-arithmetic operator overloadings.
Definition at line 157 of file Builders.h.
operator+=() [2/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator+= (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 411 of file Builders.h.
operator-() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator- (Value e)
Definition at line 130 of file Builders.h.
operator-() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator- (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 388 of file Builders.h.
operator-=() [1/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator-= (Value e)
Definition at line 162 of file Builders.h.
operator-=() [2/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator-= (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 414 of file Builders.h.
operator/() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator/ (Value e)
Definition at line 140 of file Builders.h.
operator/() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator/ (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 394 of file Builders.h.
operator/=() [1/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator/= (Value e)
Definition at line 172 of file Builders.h.
operator/=() [2/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator/= (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 420 of file Builders.h.
operator<() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator< (Value e)
Definition at line 209 of file Builders.h.
operator<() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator< (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 447 of file Builders.h.
operator<=() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator<= (Value e)
Definition at line 214 of file Builders.h.
operator<=() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator<= (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 450 of file Builders.h.
operator=() [1/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator= (const TemplatedIndexedValue< Load, Store > & rhs) inline
Emits a store.
Definition at line 353 of file Builders.h.
operator=() [2/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator= (Value rhs) inline
Definition at line 356 of file Builders.h.
operator>() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator> (Value e)
Definition at line 219 of file Builders.h.
operator>() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator> (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 453 of file Builders.h.
operator>=() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator>= (Value e)
Definition at line 224 of file Builders.h.
operator>=() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator>= (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 456 of file Builders.h.
operator^() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator^ (Value e)
Definition at line 150 of file Builders.h.
operator^() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator^ (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 400 of file Builders.h.
operator^=() [1/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator^= (Value e)
Definition at line 182 of file Builders.h.
References mlir::edsc::TemplatedIndexedValue< Load, Store >::operator &&().
operator^=() [2/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator^= (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 426 of file Builders.h.
References mlir::edsc::op::operator &&(), and mlir::edsc::op::operator||().
operator||() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator|| (Value e)
Definition at line 194 of file Builders.h.
operator||() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator|| (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 436 of file Builders.h.
References mlir::edsc::op::eq(), mlir::edsc::op::ne(), mlir::operator<(), mlir::operator<=(), mlir::edsc::op::operator>(), and mlir::edsc::op::operator>=().
The documentation for this class was generated from the following file:
include/mlir/EDSC/Builders.h