MLIR: mlir::ContractionOpLowering Class Reference
mlir::ContractionOpLowering Class Reference
Progressive lowering of ContractionOp.
#include "mlir/Dialect/Vector/VectorTransforms.h"
Public Member Functions
ContractionOpLowering (vector::VectorTransformsOptions vectorTransformsOptions, MLIRContext *context)
LogicalResult matchAndRewrite (vector::ContractionOp op, PatternRewriter &rewriter) const override
Progressive lowering of ContractionOp.
Public Member Functions inherited from mlir::OpRewritePattern< vector::ContractionOp >
OpRewritePattern (MLIRContext *context, PatternBenefit benefit=1)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
void rewrite (Operation *op, PatternRewriter &rewriter) const final
Wrappers around the RewritePattern methods that pass the derived op type.
virtual void rewrite (vector::ContractionOp op, PatternRewriter &rewriter) const
Rewrite and Match methods that operate on the SourceOp type.
LogicalResult match (Operation *op) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual LogicalResult match (vector::ContractionOp op) const
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::RewritePattern
virtual bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Public Member Functions inherited from mlir::Pattern
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
OperationName getRootKind () const
Return the root node that this pattern matches.
virtual ~Pattern ()
Additional Inherited Members
Protected Member Functions inherited from mlir::RewritePattern
RewritePattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
RewritePattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
Protected Attributes inherited from mlir::RewritePattern
SmallVector< OperationName, 2 > generatedOps
A list of the potential operations that may be generated when rewriting an op with this pattern.
Detailed Description
Progressive lowering of ContractionOp.
One: x = vector.contract with at least one free/batch dimension is replaced by: a = vector.contract with one less free/batch dimension b = vector.contract with one less free/batch dimension .. x = combine a b .. until a pure contraction is reached (no free/batch dimensions), which is replaced by a fma/reduction op.
This only kicks in when either VectorTransformsOptions is set to FMA or when other contraction patterns fail.
Definition at line 152 of file VectorTransforms.h.
Constructor & Destructor Documentation
ContractionOpLowering()
mlir::ContractionOpLowering::ContractionOpLowering (vector::VectorTransformsOptions vectorTransformsOptions, MLIRContext * context) inline
Definition at line 156 of file VectorTransforms.h.
Member Function Documentation
matchAndRewrite()
LogicalResult mlir::ContractionOpLowering::matchAndRewrite (vector::ContractionOp op, PatternRewriter & rewriter) const override virtual
Progressive lowering of ContractionOp.
One: x = vector.contract with at least one free/batch dimension is replaced by: a = vector.contract with one less free/batch dimension b = vector.contract with one less free/batch dimension .. x = combine a b .. until a pure contraction is reached (no free/batch dimensions), which is replaced by a fma/reduction op.
TODO(ajcbik): break down into transpose/reshape/cast ops when they become available to avoid code dup TODO(ajcbik): investigate lowering order impact on performance
Reimplemented from mlir::OpRewritePattern< vector::ContractionOp >.
Definition at line 1725 of file VectorTransforms.cpp.
References adjustIter(), adjustMap(), mlir::PatternRewriter::create(), mlir::failure(), mlir::Builder::getAffineMapArrayAttr(), mlir::Builder::getArrayAttr(), mlir::Value::getLoc(), getResultIndex(), mlir::Builder::getStringAttr(), mlir::Builder::getZeroAttr(), mlir::Type::isa(), mlir::ContractionOpToMatmulOpLowering::match(), mlir::ContractionOpToOuterProductOpLowering::match(), mlir::PatternRewriter::replaceOp(), reshapeLoad(), reshapeStore(), mlir::succeeded(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Vector/VectorTransforms.h
lib/Dialect/Vector/VectorTransforms.cpp