MLIR: mlir::DenseIntOrFPElementsAttr Class Reference
mlir::DenseIntOrFPElementsAttr Class Reference
An attribute class for specializing behavior of Int and Floating-point densely packed string arrays.
#include "mlir/IR/Attributes.h"
Static Public Member Functions
static bool kindof (unsigned kind)
Method for support type inquiry through isa, cast and dyn_cast.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Static Protected Member Functions
static DenseElementsAttr getRaw (ShapedType type, size_t storageWidth, ArrayRef< APFloat > values, bool isSplat)
Constructs a dense elements attribute from an array of raw APFloat values.
static DenseElementsAttr getRaw (ShapedType type, size_t storageWidth, ArrayRef< APInt > values, bool isSplat)
Constructs a dense elements attribute from an array of raw APInt values.
static DenseElementsAttr getRaw (ShapedType type, ArrayRef< char > data, bool isSplat)
Get or create a new dense elements attribute instance with the given raw data buffer.
static DenseElementsAttr getRawComplex (ShapedType type, ArrayRef< char > data, int64_t dataEltSize, bool isInt, bool isSigned)
Overload of the raw 'get' method that asserts that the given type is of complex type.
static DenseElementsAttr getRawIntOrFloat (ShapedType type, ArrayRef< char > data, int64_t dataEltSize, bool isInt, bool isSigned)
Overload of the raw 'get' method that asserts that the given type is of integer or floating-point type.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Protected Attributes
friend DenseElementsAttr
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Detailed Description
An attribute class for specializing behavior of Int and Floating-point densely packed string arrays.
Definition at line 1194 of file Attributes.h.
Member Function Documentation
getRaw() [1/3]
DenseElementsAttr DenseIntOrFPElementsAttr::getRaw (ShapedType type, size_t storageWidth, ArrayRef< APFloat > values, bool isSplat) static protected
Constructs a dense elements attribute from an array of raw APFloat values.
Each APFloat value is expected to have the same bitwidth as the element type of 'type'. 'type' must be a vector or tensor with static shape.
Definition at line 1068 of file Attributes.cpp.
References writeAPIntsToBuffer().
Referenced by mlir::DenseElementsAttr::get(), mlir::DenseElementsAttr::getFromRawBuffer(), getRaw(), and mlir::DenseElementsAttr::reshape().
getRaw() [2/3]
DenseElementsAttr DenseIntOrFPElementsAttr::getRaw (ShapedType type, size_t storageWidth, ArrayRef< APInt > values, bool isSplat) static protected
Constructs a dense elements attribute from an array of raw APInt values.
Each APInt value is expected to have the same bitwidth as the element type of 'type'. 'type' must be a vector or tensor with static shape.
Each APInt value is expected to have the same bitwidth as the element type of 'type'.
Definition at line 1081 of file Attributes.cpp.
References getRaw(), and writeAPIntsToBuffer().
getRaw() [3/3]
DenseElementsAttr DenseIntOrFPElementsAttr::getRaw (ShapedType type, ArrayRef< char > data, bool isSplat) static protected
Get or create a new dense elements attribute instance with the given raw data buffer.
'type' must be a vector or tensor with static shape.
Definition at line 1090 of file Attributes.cpp.
References mlir::StandardAttributes::DenseIntOrFPElements, mlir::Type::getContext(), mlir::ShapedType::hasStaticShape(), and mlir::Type::isa().
getRawComplex()
DenseElementsAttr DenseIntOrFPElementsAttr::getRawComplex (ShapedType type, ArrayRef< char > data, int64_t dataEltSize, bool isInt, bool isSigned) static protected
Overload of the raw 'get' method that asserts that the given type is of complex type.
This method is used to verify type invariants that the templatized 'get' method cannot.
Definition at line 1103 of file Attributes.cpp.
References mlir::Type::cast(), mlir::ShapedType::getElementType(), getElementType(), mlir::ShapedType::getNumElements(), and isValidIntOrFloat().
Referenced by mlir::DenseElementsAttr::getRawComplex().
getRawIntOrFloat()
DenseElementsAttr DenseIntOrFPElementsAttr::getRawIntOrFloat (ShapedType type, ArrayRef< char > data, int64_t dataEltSize, bool isInt, bool isSigned) static protected
Overload of the raw 'get' method that asserts that the given type is of integer or floating-point type.
Overload of the 'getRaw' method that asserts that the given type is of integer type.
This method is used to verify type invariants that the templatized 'get' method cannot.
Definition at line 1121 of file Attributes.cpp.
References mlir::ShapedType::getElementType(), mlir::ShapedType::getNumElements(), and isValidIntOrFloat().
Referenced by mlir::DenseElementsAttr::getRawIntOrFloat().
kindof()
static bool mlir::DenseIntOrFPElementsAttr::kindof (unsigned kind) inline static
Method for support type inquiry through isa, cast and dyn_cast.
Definition at line 1202 of file Attributes.h.
References mlir::StandardAttributes::DenseIntOrFPElements.
Member Data Documentation
DenseElementsAttr
friend mlir::DenseIntOrFPElementsAttr::DenseElementsAttr protected
Definition at line 1207 of file Attributes.h.
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp