MLIR: mlir::edsc::GenericLoopNestRangeBuilder< LoopTy > Class Template Reference
mlir::edsc::GenericLoopNestRangeBuilder< LoopTy > Class Template Reference
Helper template class for building scf.for and affine.loop nests from ranges.
#include "mlir/Dialect/Linalg/EDSC/Builders.h"
Public Member Functions
GenericLoopNestRangeBuilder (MutableArrayRef< Value > ivs, ArrayRef< SubViewOp::Range > ranges)
void operator() (std::function< void(void)> fun=nullptr)
template<>
GenericLoopNestRangeBuilder (MutableArrayRef< Value > ivs, ArrayRef< SubViewOp::Range > ranges)
template<>
GenericLoopNestRangeBuilder (MutableArrayRef< Value > ivs, ArrayRef< SubViewOp::Range > ranges)
template<>
GenericLoopNestRangeBuilder (MutableArrayRef< Value > ivs, ArrayRef< SubViewOp::Range > ranges)
Detailed Description
template<typename LoopTy>
class mlir::edsc::GenericLoopNestRangeBuilder< LoopTy >
Helper template class for building scf.for and affine.loop nests from ranges.
Definition at line 40 of file Builders.h.
Constructor & Destructor Documentation
GenericLoopNestRangeBuilder() [1/4]
template<typename LoopTy > mlir::edsc::GenericLoopNestRangeBuilder< LoopTy >::GenericLoopNestRangeBuilder (MutableArrayRef< Value > ivs, ArrayRef< SubViewOp::Range > ranges)
GenericLoopNestRangeBuilder() [2/4]
template<> mlir::edsc::GenericLoopNestRangeBuilder< scf::ForOp >::GenericLoopNestRangeBuilder (MutableArrayRef< Value > ivs, ArrayRef< SubViewOp::Range > ranges)
Definition at line 39 of file Builders.cpp.
References unpackRanges().
GenericLoopNestRangeBuilder() [3/4]
template<> mlir::edsc::GenericLoopNestRangeBuilder< AffineForOp >::GenericLoopNestRangeBuilder (MutableArrayRef< Value > ivs, ArrayRef< SubViewOp::Range > ranges)
Definition at line 47 of file Builders.cpp.
References unpackRanges().
GenericLoopNestRangeBuilder() [4/4]
template<> mlir::edsc::GenericLoopNestRangeBuilder< scf::ParallelOp >::GenericLoopNestRangeBuilder (MutableArrayRef< Value > ivs, ArrayRef< SubViewOp::Range > ranges)
Definition at line 63 of file Builders.cpp.
References unpackRanges().
Member Function Documentation
operator()()
template<typename LoopTy > void mlir::edsc::GenericLoopNestRangeBuilder< LoopTy >::operator() (std::function< void(void)> fun = nullptr) inline
Definition at line 44 of file Builders.h.
The documentation for this class was generated from the following file:
include/mlir/Dialect/Linalg/EDSC/Builders.h