MLIR: mlir::spirv::PointerType Class Reference
mlir::spirv::PointerType Class Reference
#include "mlir/Dialect/SPIRV/SPIRVTypes.h"
Public Member Functions
Type getPointeeType () const
StorageClass getStorageClass () const
void getExtensions (SPIRVType::ExtensionArrayRefVector &extensions, Optional< spirv::StorageClass > storage=llvm::None)
void getCapabilities (SPIRVType::CapabilityArrayRefVector &capabilities, Optional< spirv::StorageClass > storage=llvm::None)
Static Public Member Functions
static bool kindof (unsigned kind)
static PointerType get (Type pointeeType, StorageClass storageClass)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 228 of file SPIRVTypes.h.
Member Function Documentation
get()
PointerType PointerType::get (Type pointeeType, StorageClass storageClass) static
Definition at line 579 of file SPIRVTypes.cpp.
References mlir::Type::getContext(), and mlir::spirv::TypeKind::Pointer.
Referenced by convertMemrefType(), createGlobalVarForEntryPointArgument(), getElementPtrType(), getOrInsertBuiltinVariable(), isFnEntryBlock(), parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), parseLoadOp(), parsePointerType(), and parseStoreOp().
getCapabilities()
void PointerType::getCapabilities (SPIRVType::CapabilityArrayRefVector & capabilities, Optional< spirv::StorageClass > storage = llvm::None)
Definition at line 604 of file SPIRVTypes.cpp.
getExtensions()
void PointerType::getExtensions (SPIRVType::ExtensionArrayRefVector & extensions, Optional< spirv::StorageClass > storage = llvm::None)
Definition at line 590 of file SPIRVTypes.cpp.
getPointeeType()
Type PointerType::getPointeeType () const
Definition at line 584 of file SPIRVTypes.cpp.
Referenced by print().
getStorageClass()
StorageClass PointerType::getStorageClass () const
Definition at line 586 of file SPIRVTypes.cpp.
Referenced by mlir::VulkanLayoutUtils::isLegalType(), and print().
kindof()
static bool mlir::spirv::PointerType::kindof (unsigned kind) inline static
Definition at line 233 of file SPIRVTypes.h.
References mlir::StandardTypes::None, and mlir::spirv::TypeKind::Pointer.
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/SPIRVTypes.h
lib/Dialect/SPIRV/SPIRVTypes.cpp