MLIR: mlir::AffineMapAttr Class Reference
mlir::AffineMapAttr Class Reference
#include "mlir/IR/Attributes.h"
Public Types
using ValueType = AffineMap
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
AffineMap getValue () const
Static Public Member Functions
static AffineMapAttr get (AffineMap value)
static bool kindof (unsigned kind)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 177 of file Attributes.h.
Member Typedef Documentation
ValueType
using mlir::AffineMapAttr::ValueType = AffineMap
Definition at line 182 of file Attributes.h.
Member Function Documentation
get()
AffineMapAttr AffineMapAttr::get (AffineMap value) static
Definition at line 56 of file Attributes.cpp.
References mlir::StandardAttributes::AffineMap, and mlir::AffineMap::getContext().
Referenced by mlir::AffineDmaStartOp::build(), mlir::AffineDmaWaitOp::build(), canonicalizeLoopBounds(), canRegisterAlias(), collapseReassociationMaps(), mlir::AffineDmaWaitOp::fold(), foldMinMaxOp(), fuseLinalgOpsGreedily(), mlir::Builder::getAffineMapArrayAttr(), getLibraryCallSymbolRef(), mlir::gpu::getParallelLoopDimMappingAttr(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::indexing_maps(), mlir::linalg::interchange(), mlir::isColumnMajorMatmul(), mlir::isRowMajorMatmul(), isTensorReshapeOpFusible(), mlir::detail::Parser::parseAttribute(), parseBound(), mlir::detail::Parser::parseToken(), parseTransferReadOp(), parseTransferWriteOp(), parseTransposeOp(), print(), mlir::replaceAllMemRefUsesWith(), replaceUnitDims(), replaceUnitExtents(), verify(), and verifyTransferOp().
getValue()
AffineMap AffineMapAttr::getValue () const
Definition at line 60 of file Attributes.cpp.
Referenced by getDimMap(), mlir::AffineDmaStartOp::getDstMap(), getInputAndOutputIndices(), getLocalInvocationDimSize(), mlir::AffineDmaStartOp::getSrcMap(), mlir::AffineDmaStartOp::getTagMap(), mlir::AffineDmaWaitOp::getTagMap(), mlir::AffineDmaStartOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAffineApplyOp(), parseAffineParallelOp(), printBound(), printDenseElementsAttrImpl(), tileLinalgOpImpl(), verify(), and verifyMemoryOpIndexing().
kindof()
static bool mlir::AffineMapAttr::kindof (unsigned kind) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 189 of file Attributes.h.
References mlir::StandardAttributes::AffineMap.
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp