MLIR: mlir::UnitAttr Class Reference
mlir::UnitAttr Class Reference
Unit attributes are attributes that hold no specific value and are given meaning by their existence.
#include "mlir/IR/Attributes.h"
Static Public Member Functions
static UnitAttr get (MLIRContext *context)
static bool kindof (unsigned kind)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Unit attributes are attributes that hold no specific value and are given meaning by their existence.
Definition at line 591 of file Attributes.h.
Member Function Documentation
get()
UnitAttr UnitAttr::get (MLIRContext * context) static
Definition at line 751 of file MLIRContext.cpp.
References mlir::MLIRContext::getImpl(), and mlir::MLIRContextImpl::unitAttr.
Referenced by convertToLaunchFuncOp(), getLibraryCallSymbolRef(), and mlir::Builder::getUnitAttr().
kindof()
static bool mlir::UnitAttr::kindof (unsigned kind) inline static
Definition at line 597 of file Attributes.h.
References mlir::StandardAttributes::Unit.
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/MLIRContext.cpp