MLIR: mlir::IndexType Class Reference
mlir::IndexType Class Reference
Index is a special integer-like type with unknown platform-dependent bit width.
#include "mlir/IR/StandardTypes.h"
Static Public Member Functions
static IndexType get (MLIRContext *context)
Get an instance of the IndexType.
static bool kindof (unsigned kind)
Support method to enable LLVM-style type casting.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Static Public Attributes
static constexpr unsigned kInternalStorageBitWidth = 64
Storage bit width used for IndexType by internal compiler data structures.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Index is a special integer-like type with unknown platform-dependent bit width.
Definition at line 105 of file StandardTypes.h.
Member Function Documentation
get()
IndexType IndexType::get (MLIRContext * context) static
Get an instance of the IndexType.
Definition at line 665 of file MLIRContext.cpp.
References mlir::MLIRContext::getImpl(), and mlir::MLIRContextImpl::indexTy.
Referenced by mlir::AffineMap::constantFold(), extractOperandTypes< IndexedGenericOp >(), mlir::AffineDmaWaitOp::fold(), foldMinMaxOp(), mlir::Builder::getIndexArrayAttr(), mlir::Builder::getIndexType(), makeIndexType(), mlir::LLVMTypeConverter::promoteOneMemRefDescriptor(), and verify().
kindof()
static bool mlir::IndexType::kindof (unsigned kind) inline static
Support method to enable LLVM-style type casting.
Definition at line 113 of file StandardTypes.h.
References mlir::StandardTypes::Index.
Member Data Documentation
kInternalStorageBitWidth
constexpr unsigned mlir::IndexType::kInternalStorageBitWidth = 64 static
Storage bit width used for IndexType by internal compiler data structures.
Definition at line 116 of file StandardTypes.h.
Referenced by buildAttributeAPInt(), mlir::IntegerAttr::get(), and mlir::detail::getDenseElementBitWidth().
The documentation for this class was generated from the following files:
include/mlir/IR/StandardTypes.h
lib/IR/MLIRContext.cpp