MLIR: mlir::edsc::LoopBuilder Class Reference
mlir::edsc::LoopBuilder Class Reference
A LoopBuilder is a generic NestedBuilder for loop-like MLIR operations.
#include "mlir/EDSC/Builders.h"
Public Member Functions
LoopBuilder (const LoopBuilder &)=delete
LoopBuilder (LoopBuilder &&)=default
LoopBuilder & operator= (const LoopBuilder &)=delete
LoopBuilder & operator= (LoopBuilder &&)=default
void operator() (function_ref< void(void)> fun=nullptr)
The only purpose of this operator is to serve as a sequence point so that the evaluation of fun (which build IR snippets in a scoped fashion) is scoped within a LoopBuilder.
void setOp (Operation *op)
Operation * getOp ()
Friends
LoopBuilder makeAffineLoopBuilder (Value *iv, ArrayRef< Value > lbs, ArrayRef< Value > ubs, int64_t step)
Constructs a new AffineForOp and captures the associated induction variable.
LoopBuilder makeParallelLoopBuilder (MutableArrayRef< Value > ivs, ArrayRef< Value > lbs, ArrayRef< Value > ubs, ArrayRef< Value > steps)
Constructs a new scf::ParallelOp and captures the associated induction variables.
LoopBuilder makeLoopBuilder (Value *iv, Value lb, Value ub, Value step, MutableArrayRef< Value > iterArgsHandles, ValueRange iterArgsInitValues)
Constructs a new scf::ForOp and captures the associated induction variable.
Additional Inherited Members
Protected Member Functions inherited from mlir::edsc::NestedBuilder
NestedBuilder ()=default
NestedBuilder (const NestedBuilder &)=delete
NestedBuilder (NestedBuilder &&other)
NestedBuilder & operator= (const NestedBuilder &)=delete
NestedBuilder & operator= (NestedBuilder &&other)
void enter (mlir::Block *block)
Enter an mlir::Block and setup a ScopedContext to insert operations at the end of it.
void exit ()
Exit the current mlir::Block by explicitly deleting the dynamically allocated OpBuilder and ScopedContext.
~NestedBuilder ()
Custom destructor does nothing because we already destroyed bodyScope manually in exit.
Detailed Description
A LoopBuilder is a generic NestedBuilder for loop-like MLIR operations.
More specifically it is meant to be used as a temporary object for representing any nested MLIR construct that is "related to" an mlir::Value (for now an induction variable). This is extensible and will evolve in the future as MLIR evolves, hence the name LoopBuilder (as opposed to say ForBuilder or AffineForBuilder).
Definition at line 156 of file Builders.h.
Constructor & Destructor Documentation
LoopBuilder() [1/2]
mlir::edsc::LoopBuilder::LoopBuilder (const LoopBuilder &) delete
LoopBuilder() [2/2]
mlir::edsc::LoopBuilder::LoopBuilder (LoopBuilder &&) default
Member Function Documentation
getOp()
Operation* mlir::edsc::LoopBuilder::getOp () inline
Definition at line 169 of file Builders.h.
References mlir::edsc::makeAffineLoopBuilder(), mlir::edsc::makeLoopBuilder(), and mlir::edsc::makeParallelLoopBuilder().
operator()()
void mlir::edsc::LoopBuilder::operator() (function_ref< void(void)> fun = nullptr)
The only purpose of this operator is to serve as a sequence point so that the evaluation of fun (which build IR snippets in a scoped fashion) is scoped within a LoopBuilder.
The particular use case concerns nested blocks:
{c++}
   For (&i, lb, ub, 1)({
     /--- destructor for this `For` is not always called before ...
     V
     For (&j1, lb, ub, 1)({
       some_op_1,
     }),
     /--- ... this scope is entered, resulting in improperly nested IR.
     V
     For (&j2, lb, ub, 1)({
       some_op_2,
     }),
   });
Definition at line 90 of file Builders.cpp.
operator=() [1/2]
LoopBuilder& mlir::edsc::LoopBuilder::operator= (const LoopBuilder &) delete
operator=() [2/2]
LoopBuilder& mlir::edsc::LoopBuilder::operator= (LoopBuilder &&) default
setOp()
void mlir::edsc::LoopBuilder::setOp (Operation * op) inline
Definition at line 168 of file Builders.h.
Referenced by mlir::edsc::makeLoopBuilder().
Friends And Related Function Documentation
makeAffineLoopBuilder
LoopBuilder makeAffineLoopBuilder (Value * iv, ArrayRef< Value > lbs, ArrayRef< Value > ubs, int64_t step) friend
Constructs a new AffineForOp and captures the associated induction variable.
A Value pointer is passed as the first argument and is the only way to capture the loop induction variable.
makeLoopBuilder
LoopBuilder makeLoopBuilder (Value * iv, Value lb, Value ub, Value step, MutableArrayRef< Value > iterArgsHandles, ValueRange iterArgsInitValues) friend
Constructs a new scf::ForOp and captures the associated induction variable.
A Value pointer is passed as the first argument and is the only way to capture the loop induction variable.
makeParallelLoopBuilder
LoopBuilder makeParallelLoopBuilder (MutableArrayRef< Value > ivs, ArrayRef< Value > lbs, ArrayRef< Value > ubs, ArrayRef< Value > steps) friend
Constructs a new scf::ParallelOp and captures the associated induction variables.
An array of Value pointers is passed as the first argument and is the only way to capture loop induction variables.
The documentation for this class was generated from the following files:
include/mlir/EDSC/Builders.h
lib/EDSC/Builders.cpp