MLIR: mlir::spirv::RuntimeArrayType Class Reference
mlir::spirv::RuntimeArrayType Class Reference
#include "mlir/Dialect/SPIRV/SPIRVTypes.h"
Public Member Functions
Type getElementType () const
unsigned getArrayStride () const
Returns the array stride in bytes.
void getExtensions (SPIRVType::ExtensionArrayRefVector &extensions, Optional< spirv::StorageClass > storage=llvm::None)
void getCapabilities (SPIRVType::CapabilityArrayRefVector &capabilities, Optional< spirv::StorageClass > storage=llvm::None)
Static Public Member Functions
static bool kindof (unsigned kind)
static RuntimeArrayType get (Type elementType)
static RuntimeArrayType get (Type elementType, unsigned stride)
Returns a runtime array type with the given stride in bytes.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 248 of file SPIRVTypes.h.
Member Function Documentation
get() [1/2]
RuntimeArrayType RuntimeArrayType::get (Type elementType) static
Definition at line 642 of file SPIRVTypes.cpp.
References mlir::Type::getContext(), and mlir::spirv::TypeKind::RuntimeArray.
Referenced by convertMemrefType(), mlir::VulkanLayoutUtils::decorateType(), isFnEntryBlock(), and parseRuntimeArrayType().
get() [2/2]
RuntimeArrayType RuntimeArrayType::get (Type elementType, unsigned stride) static
Returns a runtime array type with the given stride in bytes.
Definition at line 647 of file SPIRVTypes.cpp.
References mlir::Type::getContext(), and mlir::spirv::TypeKind::RuntimeArray.
getArrayStride()
unsigned RuntimeArrayType::getArrayStride () const
Returns the array stride in bytes.
0 means no stride decorated on this type.
Definition at line 654 of file SPIRVTypes.cpp.
Referenced by print().
getCapabilities()
void RuntimeArrayType::getCapabilities (SPIRVType::CapabilityArrayRefVector & capabilities, Optional< spirv::StorageClass > storage = llvm::None)
Definition at line 664 of file SPIRVTypes.cpp.
References mlir::Type::cast(), and getElementType().
getElementType()
Type RuntimeArrayType::getElementType () const
Definition at line 652 of file SPIRVTypes.cpp.
Referenced by mlir::VulkanLayoutUtils::decorateType(), and print().
getExtensions()
void RuntimeArrayType::getExtensions (SPIRVType::ExtensionArrayRefVector & extensions, Optional< spirv::StorageClass > storage = llvm::None)
Definition at line 658 of file SPIRVTypes.cpp.
References mlir::Type::cast(), and getElementType().
kindof()
static bool mlir::spirv::RuntimeArrayType::kindof (unsigned kind) inline static
Definition at line 254 of file SPIRVTypes.h.
References getElementType(), mlir::StandardTypes::None, and mlir::spirv::TypeKind::RuntimeArray.
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/SPIRVTypes.h
lib/Dialect/SPIRV/SPIRVTypes.cpp