MLIR: mlir::edsc::BlockBuilder Class Reference
mlir::edsc::BlockBuilder Class Reference
A BlockBuilder is a NestedBuilder for mlir::Block*.
#include "mlir/EDSC/Builders.h"
Public Member Functions
BlockBuilder (BlockHandle bh, Append)
Enters the mlir::Block* previously captured by bh and sets the insertion point to its end.
BlockBuilder (BlockHandle *bh)
Constructs a new mlir::Block with argument types derived from args.
BlockBuilder (BlockHandle *bh, ArrayRef< Type > types, MutableArrayRef< Value > args)
BlockBuilder (BlockHandle *bh, Region &region, ArrayRef< Type > types, MutableArrayRef< Value > args)
Constructs a new mlir::Block with argument types derived from args and appends it as the last block in the region.
void operator() (function_ref< void(void)> fun=nullptr)
The only purpose of this operator is to serve as a sequence point so that the evaluation of fun (which build IR snippets in a scoped fashion) is scoped within a BlockBuilder.
Additional Inherited Members
Protected Member Functions inherited from mlir::edsc::NestedBuilder
NestedBuilder ()=default
NestedBuilder (const NestedBuilder &)=delete
NestedBuilder (NestedBuilder &&other)
NestedBuilder & operator= (const NestedBuilder &)=delete
NestedBuilder & operator= (NestedBuilder &&other)
void enter (mlir::Block *block)
Enter an mlir::Block and setup a ScopedContext to insert operations at the end of it.
void exit ()
Exit the current mlir::Block by explicitly deleting the dynamically allocated OpBuilder and ScopedContext.
~NestedBuilder ()
Custom destructor does nothing because we already destroyed bodyScope manually in exit.
Detailed Description
A BlockBuilder is a NestedBuilder for mlir::Block*.
This exists by opposition to LoopBuilder which is not related to an mlir::Block* but to a mlir::Value. It is meant to be used as a temporary object for representing any nested MLIR construct that is "related to" an mlir::Block*.
Definition at line 195 of file Builders.h.
Constructor & Destructor Documentation
BlockBuilder() [1/4]
mlir::edsc::BlockBuilder::BlockBuilder (BlockHandle bh, Append)
Enters the mlir::Block* previously captured by bh and sets the insertion point to its end.
If the block already contains a terminator, set the insertion point before the terminator.
Definition at line 114 of file Builders.cpp.
References mlir::edsc::BlockHandle::getBlock().
BlockBuilder() [2/4]
mlir::edsc::BlockBuilder::BlockBuilder (BlockHandle * bh) inline
Constructs a new mlir::Block with argument types derived from args.
Captures the new block in bh and its arguments into args. Enters the new mlir::Block* and sets the insertion point to its end.
Prerequisites: The Value args are typed delayed Values; i.e. they are not yet bound to mlir::Value.
Definition at line 209 of file Builders.h.
BlockBuilder() [3/4]
mlir::edsc::BlockBuilder::BlockBuilder (BlockHandle * bh, ArrayRef< Type > types, MutableArrayRef< Value > args)
Definition at line 119 of file Builders.cpp.
References mlir::edsc::BlockHandle::create(), mlir::Block::getArguments(), and mlir::edsc::BlockHandle::getBlock().
BlockBuilder() [4/4]
mlir::edsc::BlockBuilder::BlockBuilder (BlockHandle * bh, Region & region, ArrayRef< Type > types, MutableArrayRef< Value > args)
Constructs a new mlir::Block with argument types derived from args and appends it as the last block in the region.
Captures the new block in bh and its arguments into args. Enters the new mlir::Block* and sets the insertion point to its end.
Prerequisites: The Value args are typed delayed Values; i.e. they are not yet bound to mlir::Value.
Definition at line 133 of file Builders.cpp.
References mlir::edsc::BlockHandle::createInRegion(), mlir::Block::getArguments(), and mlir::edsc::BlockHandle::getBlock().
Member Function Documentation
operator()()
void mlir::edsc::BlockBuilder::operator() (function_ref< void(void)> fun = nullptr)
The only purpose of this operator is to serve as a sequence point so that the evaluation of fun (which build IR snippets in a scoped fashion) is scoped within a BlockBuilder.
Only serves as an ordering point between entering nested block and creating stmts.
Definition at line 150 of file Builders.cpp.
The documentation for this class was generated from the following files:
include/mlir/EDSC/Builders.h
lib/EDSC/Builders.cpp