MLIR: mlir::IntegerType Class Reference
mlir::IntegerType Class Reference
Integer types can have arbitrary bitwidth up to a large fixed limit.
#include "mlir/IR/StandardTypes.h"
Public Types
enum SignednessSemantics { Signless, Signed, Unsigned }
Signedness semantics.
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
unsigned getWidth () const
Return the bitwidth of this integer type.
SignednessSemantics getSignedness () const
Return the signedness semantics of this integer type.
bool isSignless () const
Return true if this is a signless integer type.
bool isSigned () const
Return true if this is a signed integer type.
bool isUnsigned () const
Return true if this is an unsigned integer type.
Static Public Member Functions
static IntegerType get (unsigned width, MLIRContext *context)
Get or create a new IntegerType of the given width within the context.
static IntegerType get (unsigned width, SignednessSemantics signedness, MLIRContext *context)
Get or create a new IntegerType of the given width within the context.
static IntegerType getChecked (unsigned width, Location location)
Get or create a new IntegerType of the given width within the context, defined at the given, potentially unknown, location.
static IntegerType getChecked (unsigned width, SignednessSemantics signedness, Location location)
Get or create a new IntegerType of the given width within the context, defined at the given, potentially unknown, location.
static LogicalResult verifyConstructionInvariants (Location loc, unsigned width, SignednessSemantics signedness)
Verify the construction of an integer type.
static bool kindof (unsigned kind)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Static Public Attributes
static constexpr unsigned kMaxWidth = 4096
Integer representation maximal bitwidth.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Integer types can have arbitrary bitwidth up to a large fixed limit.
Definition at line 124 of file StandardTypes.h.
Member Enumeration Documentation
SignednessSemantics
enum mlir::IntegerType::SignednessSemantics
Signedness semantics.
Enumerator
Signless
Signed
No signedness semantics.
Unsigned
Signed integer.
Definition at line 130 of file StandardTypes.h.
Member Function Documentation
get() [1/2]
IntegerType IntegerType::get (unsigned width, MLIRContext * context) static
Get or create a new IntegerType of the given width within the context.
The created IntegerType is signless (i.e., no signedness semantics). Assume the width is within the allowed range and assert on failures. Use getChecked to handle failures gracefully.
Definition at line 696 of file MLIRContext.cpp.
References Signless.
Referenced by allocBuffer(), mlir::applyCmpPredicate(), mlir::quant::UniformQuantizedPerAxisValueConverter::convert(), convertRangeType(), convertScalarType(), diag(), mlir::spirv::getDefaultResourceLimits(), getDefaultStorageParams(), mlir::spirv::getEntryPointABIAttr(), getI1SameShape(), mlir::Builder::getI1Type(), mlir::Builder::getI32Type(), mlir::Builder::getI64Type(), mlir::SPIRVTypeConverter::getIndexType(), mlir::Builder::getIntegerType(), getPhiIncomingBlock(), isFnEntryBlock(), mlir::edsc::makeGenericLinalgOp(), and makeI64ArrayAttr().
get() [2/2]
IntegerType IntegerType::get (unsigned width, IntegerType::SignednessSemantics signedness, MLIRContext * context) static
Get or create a new IntegerType of the given width within the context.
The created IntegerType has signedness semantics as indicated via signedness. Assume the width is within the allowed range and assert on failures. Use getChecked to handle failures gracefully.
Definition at line 700 of file MLIRContext.cpp.
References getCachedIntegerType(), and mlir::StandardTypes::Integer.
getChecked() [1/2]
IntegerType IntegerType::getChecked (unsigned width, Location location) static
Get or create a new IntegerType of the given width within the context, defined at the given, potentially unknown, location.
The created IntegerType is signless (i.e., no signedness semantics). If the width is outside the allowed range, emit errors and return a null type.
Definition at line 708 of file MLIRContext.cpp.
References Signless.
Referenced by mlir::detail::Parser::parseNonFunctionType().
getChecked() [2/2]
IntegerType IntegerType::getChecked (unsigned width, SignednessSemantics signedness, Location location) static
Get or create a new IntegerType of the given width within the context, defined at the given, potentially unknown, location.
The created IntegerType has signedness semantics as indicated via signedness. If the width is outside the allowed range, emit errors and return a null type.
Definition at line 712 of file MLIRContext.cpp.
References getCachedIntegerType(), mlir::Attribute::getContext(), and mlir::StandardTypes::Integer.
getSignedness()
IntegerType::SignednessSemantics IntegerType::getSignedness () const
Return the signedness semantics of this integer type.
Definition at line 135 of file StandardTypes.cpp.
getWidth()
unsigned IntegerType::getWidth () const
Return the bitwidth of this integer type.
Definition at line 133 of file StandardTypes.cpp.
Referenced by convertIntegerAttr(), getAtomicOpScope(), mlir::LLVMTypeConverter::getIndexType(), mlir::Builder::getZeroAttr(), mlir::spirv::ScalarType::isValid(), parseStorageRange(), parseStorageType(), printDenseElementsAttrImpl(), and verify().
isSigned()
bool mlir::IntegerType::isSigned () const inline
Return true if this is a signed integer type.
Definition at line 176 of file StandardTypes.h.
References mlir::quant::QuantizationFlags::Signed.
Referenced by isValidIntOrFloat().
isSignless()
bool mlir::IntegerType::isSignless () const inline
Return true if this is a signless integer type.
Definition at line 174 of file StandardTypes.h.
isUnsigned()
bool mlir::IntegerType::isUnsigned () const inline
Return true if this is an unsigned integer type.
Definition at line 178 of file StandardTypes.h.
kindof()
static bool mlir::IntegerType::kindof (unsigned kind) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 181 of file StandardTypes.h.
References mlir::StandardTypes::Integer.
verifyConstructionInvariants()
LogicalResult IntegerType::verifyConstructionInvariants (Location loc, unsigned width, SignednessSemantics signedness) static
Verify the construction of an integer type.
Definition at line 124 of file StandardTypes.cpp.
References mlir::emitError(), kMaxWidth, and mlir::success().
Member Data Documentation
kMaxWidth
constexpr unsigned IntegerType::kMaxWidth = 4096 static
Integer representation maximal bitwidth.
Definition at line 184 of file StandardTypes.h.
Referenced by mlir::ComplexType::getElementType(), mlir::detail::Parser::parseNonFunctionType(), and verifyConstructionInvariants().
The documentation for this class was generated from the following files:
include/mlir/IR/StandardTypes.h
lib/IR/MLIRContext.cpp
lib/IR/StandardTypes.cpp