MLIR: mlir::ContractionOpToOuterProductOpLowering Class Reference
mlir::ContractionOpToOuterProductOpLowering Class Reference
Progressive lowering of a vector.contract a, b, c with row-major matmul semantics to a reduction_size-unrolled sequence: ``` at = vector.transpose a, [1, 0] bRow0 = vector.extract b[0] atRow0 = vector.extract at[0] c0 = vector.outerproduct atRow0, bRow0, c ...
#include "mlir/Dialect/Vector/VectorTransforms.h"
Public Member Functions
ContractionOpToOuterProductOpLowering (vector::VectorTransformsOptions vectorTransformsOptions, MLIRContext *context)
LogicalResult match (vector::ContractionOp op) const override
Progressively lower a vector.contract a, b, c with row-major matmul semantics to a reduction_size-unrolled sequence: ``` at = vector.transpose a, [1, 0] bRow0 = vector.extract b[0] atRow0 = vector.extract at[0] c0 = vector.outerproduct atRow0, bRow0, c ...
void rewrite (vector::ContractionOp op, PatternRewriter &rewriter) const override
Rewrite and Match methods that operate on the SourceOp type.
Public Member Functions inherited from mlir::OpRewritePattern< vector::ContractionOp >
OpRewritePattern (MLIRContext *context, PatternBenefit benefit=1)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
void rewrite (Operation *op, PatternRewriter &rewriter) const final
Wrappers around the RewritePattern methods that pass the derived op type.
LogicalResult match (Operation *op) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual LogicalResult matchAndRewrite (vector::ContractionOp op, PatternRewriter &rewriter) const
Public Member Functions inherited from mlir::RewritePattern
virtual bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Public Member Functions inherited from mlir::Pattern
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
OperationName getRootKind () const
Return the root node that this pattern matches.
virtual ~Pattern ()
Additional Inherited Members
Protected Member Functions inherited from mlir::RewritePattern
RewritePattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
RewritePattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
Protected Attributes inherited from mlir::RewritePattern
SmallVector< OperationName, 2 > generatedOps
A list of the potential operations that may be generated when rewriting an op with this pattern.
Detailed Description
Progressive lowering of a vector.contract a, b, c with row-major matmul semantics to a reduction_size-unrolled sequence: ``` at = vector.transpose a, [1, 0] bRow0 = vector.extract b[0] atRow0 = vector.extract at[0] c0 = vector.outerproduct atRow0, bRow0, c ...
bRowK = vector.extract b[K] atRowK = vector.extract at[K] cK = vector.outerproduct atRowK, bRowK, cK-1 ```
This only kicks in when VectorTransformsOptions is set to OuterProduct and the vector.contract op is a row-major matrix multiply.
Definition at line 119 of file VectorTransforms.h.
Constructor & Destructor Documentation
ContractionOpToOuterProductOpLowering()
mlir::ContractionOpToOuterProductOpLowering::ContractionOpToOuterProductOpLowering (vector::VectorTransformsOptions vectorTransformsOptions, MLIRContext * context) inline
Definition at line 123 of file VectorTransforms.h.
Member Function Documentation
match()
LogicalResult mlir::ContractionOpToOuterProductOpLowering::match (vector::ContractionOp op) const override virtual
Progressively lower a vector.contract a, b, c with row-major matmul semantics to a reduction_size-unrolled sequence: ``` at = vector.transpose a, [1, 0] bRow0 = vector.extract b[0] atRow0 = vector.extract at[0] c0 = vector.outerproduct atRow0, bRow0, c ...
bRowK = vector.extract b[K] atRowK = vector.extract at[K] cK = vector.outerproduct atRowK, bRowK, cK-1 ```
This only kicks in when VectorTransformsOptions is set to OuterProduct but otherwise supports any layout permutation of the matrix-multiply.
Reimplemented from mlir::OpRewritePattern< vector::ContractionOp >.
Definition at line 1606 of file VectorTransforms.cpp.
References mlir::bindDims(), mlir::failure(), mlir::AffineMap::inferFromExprList(), mlir::isParallelIterator(), mlir::isReductionIterator(), mlir::vector::OuterProduct, and mlir::success().
Referenced by mlir::ContractionOpLowering::matchAndRewrite().
rewrite()
void mlir::ContractionOpToOuterProductOpLowering::rewrite (vector::ContractionOp op, PatternRewriter & rewriter) const override virtual
Rewrite and Match methods that operate on the SourceOp type.
These must be overridden by the derived pattern class.
Reimplemented from mlir::OpRewritePattern< vector::ContractionOp >.
Definition at line 1641 of file VectorTransforms.cpp.
References mlir::bindDims(), mlir::PatternRewriter::create(), mlir::Builder::getContext(), mlir::VectorType::getShape(), mlir::AffineMap::inferFromExprList(), and mlir::PatternRewriter::replaceOp().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Vector/VectorTransforms.h
lib/Dialect/Vector/VectorTransforms.cpp