MLIR: mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT > Class Template Reference
mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT > Class Template Reference
Utility class for implementing users of storage classes uniqued by a StorageUniquer.
#include "mlir/IR/StorageUniquerSupport.h"
Inherits BaseT.
Inherited by mlir::AffineMapAttr, mlir::ArrayAttr, mlir::CallSiteLoc, mlir::ComplexType, mlir::DenseIntOrFPElementsAttr, mlir::DenseStringElementsAttr, mlir::DictionaryAttr, mlir::FileLineColLoc, mlir::FloatAttr, mlir::FloatType, mlir::FunctionType, mlir::FusedLoc, mlir::IndexType, mlir::IntegerAttr, mlir::IntegerSetAttr, mlir::IntegerType, mlir::linalg::RangeType, mlir::LLVM::LLVMType, mlir::MemRefType, mlir::NameLoc, mlir::NoneType, mlir::OpaqueAttr, mlir::OpaqueElementsAttr, mlir::OpaqueLoc, mlir::OpaqueType, mlir::quant::AnyQuantizedType, mlir::quant::UniformQuantizedPerAxisType, mlir::quant::UniformQuantizedType, mlir::RankedTensorType, mlir::shape::ComponentType, mlir::shape::ElementType, mlir::shape::ShapeType, mlir::shape::SizeType, mlir::shape::ValueShapeType, mlir::shape::WitnessType, mlir::SparseElementsAttr, mlir::spirv::ArrayType, mlir::spirv::CooperativeMatrixNVType, mlir::spirv::ImageType, mlir::spirv::InterfaceVarABIAttr, mlir::spirv::MatrixType, mlir::spirv::PointerType, mlir::spirv::RuntimeArrayType, mlir::spirv::StructType, mlir::spirv::TargetEnvAttr, mlir::spirv::VerCapExtAttr, mlir::StringAttr, mlir::SymbolRefAttr, mlir::TupleType, mlir::TypeAttr, mlir::UnitAttr, mlir::UnknownLoc, mlir::UnrankedMemRefType, mlir::UnrankedTensorType, and mlir::VectorType.
Public Types
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Static Public Member Functions
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Protected Member Functions
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
template<typename ConcreteT, typename BaseT, typename StorageT, typename UniquerT>
class mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility class for implementing users of storage classes uniqued by a StorageUniquer.
Clients are not expected to interact with this class directly.
Definition at line 35 of file StorageUniquerSupport.h.
Member Typedef Documentation
Base
template<typename ConcreteT , typename BaseT , typename StorageT , typename UniquerT > using mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >::Base = StorageUserBase<ConcreteT, BaseT, StorageT, UniquerT>
Utility declarations for the concrete attribute class.
Definition at line 40 of file StorageUniquerSupport.h.
ImplType
template<typename ConcreteT , typename BaseT , typename StorageT , typename UniquerT > using mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >::ImplType = StorageT
Definition at line 41 of file StorageUniquerSupport.h.
Member Function Documentation
classof()
template<typename ConcreteT , typename BaseT , typename StorageT , typename UniquerT > template<typename T > static bool mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >::classof (T val) inline static
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Definition at line 48 of file StorageUniquerSupport.h.
get()
template<typename ConcreteT , typename BaseT , typename StorageT , typename UniquerT > template<typename... Args> static ConcreteT mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >::get (MLIRContext * ctx, unsigned kind, Args... args) inline static protected
Get or create a new ConcreteT instance within the ctx.
This function is guaranteed to return a non null object and will assert if the arguments provided are invalid.
Definition at line 59 of file StorageUniquerSupport.h.
References mlir::detail::generateUnknownStorageLocation(), and mlir::succeeded().
Referenced by mlir::linalg::RangeType::get(), and mlir::spirv::TargetEnvAttr::get().
getChecked()
template<typename ConcreteT , typename BaseT , typename StorageT , typename UniquerT > template<typename LocationT , typename... Args> static ConcreteT mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >::getChecked (LocationT loc, unsigned kind, Args... args) inline static protected
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
If the arguments provided are invalid then emit errors and return a null object.
Definition at line 70 of file StorageUniquerSupport.h.
References mlir::failed().
getImpl()
template<typename ConcreteT , typename BaseT , typename StorageT , typename UniquerT > ImplType* mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >::getImpl () const inline protected
Utility for easy access to the storage instance.
Definition at line 84 of file StorageUniquerSupport.h.
Referenced by mlir::spirv::VerCapExtAttr::getCapabilitiesAttr(), mlir::MemRefType::getChecked(), mlir::spirv::VerCapExtAttr::getExtensionsAttr(), mlir::spirv::TargetEnvAttr::getResourceLimits(), and mlir::spirv::TargetEnvAttr::getTripleAttr().
getTypeID()
template<typename ConcreteT , typename BaseT , typename StorageT , typename UniquerT > static TypeID mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >::getTypeID () inline static
Return a unique identifier for the concrete type.
Definition at line 44 of file StorageUniquerSupport.h.
verifyConstructionInvariants()
template<typename ConcreteT , typename BaseT , typename StorageT , typename UniquerT > template<typename... Args> static LogicalResult mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >::verifyConstructionInvariants (Args... args) inline static protected
Default implementation that just returns success.
Definition at line 79 of file StorageUniquerSupport.h.
References mlir::success().
The documentation for this class was generated from the following file:
include/mlir/IR/StorageUniquerSupport.h