MLIR: lib/Conversion/SPIRVToLLVM/ConvertSPIRVToLLVM.cpp File Reference
ConvertSPIRVToLLVM.cpp File Reference
#include "mlir/Conversion/SPIRVToLLVM/ConvertSPIRVToLLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVMPass.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/SPIRV/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/SPIRVOps.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Transforms/DialectConversion.h"
Functions
static bool isUnsignedIntegerOrVector (Type type)
Returns true if the given type is an unsigned integer or vector type.
Function Documentation
isUnsignedIntegerOrVector()
static bool isUnsignedIntegerOrVector (Type type) static
Returns true if the given type is an unsigned integer or vector type.
Definition at line 32 of file ConvertSPIRVToLLVM.cpp.
References mlir::Type::dyn_cast(), mlir::failure(), mlir::Builder::getI64IntegerAttr(), mlir::Type::isUnsignedInteger(), mlir::ConversionPatternRewriter::replaceOp(), and mlir::success().