MLIR: lib/EDSC/CoreAPIs.cpp File Reference
CoreAPIs.cpp File Reference
#include "mlir-c/Core.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/IR/Types.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Parser.h"
#include "llvm/ADT/StringSwitch.h"
Functions
mlir_type_t makeMemRefType (mlir_context_t context, mlir_type_t elemType, int64_list_t sizes)
Minimal C API for exposing EDSCs to Swift, Python and other languages.
mlir_type_t makeFunctionType (mlir_context_t context, mlir_type_list_t inputs, mlir_type_list_t outputs)
Returns an mlir::FunctionType of the element type elemType and shape sizes.
mlir_type_t makeIndexType (mlir_context_t context)
Returns an mlir::IndexType.
mlir_attr_t makeIntegerAttr (mlir_type_t type, int64_t value)
Returns an mlir::IntegerAttr of the specified type that contains the given value.
mlir_attr_t makeBoolAttr (mlir_context_t context, bool value)
Returns an mlir::BoolAttr with the given value.
mlir_attr_t makeFloatAttr (mlir_context_t context, float value)
Returns an mlir::FloatAttr with the given value.
mlir_attr_t makeStringAttr (mlir_context_t context, const char *value)
Returns an mlir::StringAttr with the given value.
unsigned getFunctionArity (mlir_func_t function)
Returns the arity of function.
mlir_type_t mlirParseType (const char *type, mlir_context_t context, uint64_t *charsRead)
Parses an MLIR type from the string type in the given context.
Function Documentation
getFunctionArity()
unsigned getFunctionArity (mlir_func_t function)
Returns the arity of function.
Definition at line 80 of file CoreAPIs.cpp.
References mlir::Op< FuncOp, OpTrait::ZeroOperands, OpTrait::ZeroResult, OpTrait::OneRegion, OpTrait::IsIsolatedFromAbove, OpTrait::FunctionLike, OpTrait::AutomaticAllocationScope, OpTrait::AffineScope, CallableOpInterface::Trait, SymbolOpInterface::Trait >::getFromOpaquePointer().
makeBoolAttr()
mlir_attr_t makeBoolAttr (mlir_context_t context, bool value)
Returns an mlir::BoolAttr with the given value.
Definition at line 62 of file CoreAPIs.cpp.
References mlir::BoolAttr::get().
makeFloatAttr()
mlir_attr_t makeFloatAttr (mlir_context_t context, float value)
Returns an mlir::FloatAttr with the given value.
Definition at line 68 of file CoreAPIs.cpp.
References mlir::FloatAttr::get(), and mlir::FloatType::getF32().
makeFunctionType()
mlir_type_t makeFunctionType (mlir_context_t context, mlir_type_list_t inputs, mlir_type_list_t outputs)
Returns an mlir::FunctionType of the element type elemType and shape sizes.
Definition at line 36 of file CoreAPIs.cpp.
References mlir::FunctionType::get(), mlir::Type::getFromOpaquePointer(), mlir_type_list_t::n, and mlir_type_list_t::types.
makeIndexType()
mlir_type_t makeIndexType (mlir_context_t context)
Returns an mlir::IndexType.
Definition at line 50 of file CoreAPIs.cpp.
References mlir::IndexType::get().
makeIntegerAttr()
mlir_attr_t makeIntegerAttr (mlir_type_t type, int64_t value)
Returns an mlir::IntegerAttr of the specified type that contains the given value.
Definition at line 56 of file CoreAPIs.cpp.
References mlir::IntegerAttr::get(), and mlir::Type::getFromOpaquePointer().
makeMemRefType()
mlir_type_t makeMemRefType (mlir_context_t context, mlir_type_t elemType, int64_list_t sizes)
Minimal C API for exposing EDSCs to Swift, Python and other languages.
Returns an mlir::MemRefType of the element type elemType and shape sizes.
Definition at line 25 of file CoreAPIs.cpp.
References mlir::MemRefType::get(), mlir::Type::getFromOpaquePointer(), int64_list_t::n, and int64_list_t::values.
makeStringAttr()
mlir_attr_t makeStringAttr (mlir_context_t context, const char * value)
Returns an mlir::StringAttr with the given value.
Definition at line 74 of file CoreAPIs.cpp.
References mlir::StringAttr::get().
mlirParseType()
mlir_type_t mlirParseType (const char * type, mlir_context_t context, uint64_t * charsRead)
Parses an MLIR type from the string type in the given context.
Returns a NULL type on error. If non-NULL, charsRead will contain the number of characters that were processed by the parser.
Definition at line 85 of file CoreAPIs.cpp.
References mlir::Type::getAsOpaquePointer(), and mlir::parseType().