MLIR: lib/Transforms/Inliner.cpp File Reference
Inliner.cpp File Reference
#include "PassDetail.h"
#include "mlir/Analysis/CallGraph.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Transforms/InliningUtils.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/ADT/SCCIterator.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Parallel.h"
Macros
#define DEBUG_TYPE "inlining"
Functions
static void walkReferencedSymbolNodes (Operation *op, CallGraph &cg, DenseMap< Attribute, CallGraphNode *> &resolvedRefs, function_ref< void(CallGraphNode *, Operation *)> callback)
Walk all of the used symbol callgraph nodes referenced with the given op.
static void runTransformOnCGSCCs (const CallGraph &cg, function_ref< void(MutableArrayRef< CallGraphNode *>)> sccTransformer)
Run a given transformation over the SCCs of the callgraph in a bottom up traversal.
static void collectCallOps (iterator_range< Region::iterator > blocks, CallGraphNode *sourceNode, CallGraph &cg, SmallVectorImpl< ResolvedCall > &calls, bool traverseNestedCGNodes)
Collect all of the callable operations within the given range of blocks.
static bool shouldInline (ResolvedCall &resolvedCall)
Returns true if the given call should be inlined.
static void deleteNode (CallGraphNode *node, CGUseList &useList, CallGraph &cg, MutableArrayRef< CallGraphNode *> currentSCC)
Delete the given node and remove it from the current scc and the callgraph.
static LogicalResult inlineCallsInSCC (Inliner &inliner, CGUseList &useList, MutableArrayRef< CallGraphNode *> currentSCC)
Attempt to inline calls within the given scc.
static void canonicalizeSCC (CallGraph &cg, CGUseList &useList, MutableArrayRef< CallGraphNode *> currentSCC, MLIRContext *context, const OwningRewritePatternList &canonPatterns)
Canonicalize the nodes within the given SCC with the given set of canonicalization patterns.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "inlining"
Definition at line 26 of file Inliner.cpp.
Function Documentation
canonicalizeSCC()
static void canonicalizeSCC (CallGraph & cg, CGUseList & useList, MutableArrayRef< CallGraphNode *> currentSCC, MLIRContext * context, const OwningRewritePatternList & canonPatterns) static
Canonicalize the nodes within the given SCC with the given set of canonicalization patterns.
Definition at line 464 of file Inliner.cpp.
References mlir::applyPatternsAndFoldGreedily(), mlir::Operation::emitOpError(), mlir::ParallelDiagnosticHandler::eraseOrderIDForThread(), mlir::CallGraphNode::getCallableRegion(), mlir::CallGraphNode::hasChildren(), mlir::Operation::hasTrait(), inlineCallsInSCC(), mlir::CallGraphNode::isExternal(), mlir::MLIRContext::isMultithreadingEnabled(), runTransformOnCGSCCs(), mlir::ParallelDiagnosticHandler::setOrderIDForThread(), and mlir::succeeded().
collectCallOps()
static void collectCallOps (iterator_range< Region::iterator > blocks, CallGraphNode * sourceNode, CallGraph & cg, SmallVectorImpl< ResolvedCall > & calls, bool traverseNestedCGNodes) static
Collect all of the callable operations within the given range of blocks.
If traverseNestedCGNodes is true, this will also collect call operations inside of nested callgraph nodes.
Definition at line 278 of file Inliner.cpp.
References mlir::Region::getParentRegion(), mlir::Operation::getRegions(), mlir::CallGraphNode::isExternal(), mlir::CallGraph::lookupNode(), and mlir::CallGraph::resolveCallable().
Referenced by inlineCallsInSCC().
deleteNode()
static void deleteNode (CallGraphNode * node, CGUseList & useList, CallGraph & cg, MutableArrayRef< CallGraphNode *> currentSCC) static
Delete the given node and remove it from the current scc and the callgraph.
Definition at line 372 of file Inliner.cpp.
References mlir::Operation::erase(), mlir::CallGraph::eraseNode(), mlir::CallGraphNode::getCallableRegion(), mlir::CallGraph::getExternalNode(), and mlir::Region::getParentOp().
Referenced by inlineCallsInSCC().
inlineCallsInSCC()
static LogicalResult inlineCallsInSCC (Inliner & inliner, CGUseList & useList, MutableArrayRef< CallGraphNode *> currentSCC) static
Attempt to inline calls within the given scc.
This function returns success if any calls were inlined, failure otherwise.
Definition at line 387 of file Inliner.cpp.
References collectCallOps(), deleteNode(), mlir::OpState::erase(), mlir::failed(), mlir::failure(), mlir::CallGraphNode::getCallableRegion(), mlir::Op< ConcreteType, Traits >::getOperation(), mlir::Region::getParentOp(), mlir::inlineCall(), mlir::CallGraphNode::isExternal(), shouldInline(), and mlir::success().
Referenced by canonicalizeSCC().
runTransformOnCGSCCs()
static void runTransformOnCGSCCs (const CallGraph & cg, function_ref< void(MutableArrayRef< CallGraphNode *>)> sccTransformer) static
Run a given transformation over the SCCs of the callgraph in a bottom up traversal.
Definition at line 247 of file Inliner.cpp.
Referenced by canonicalizeSCC().
shouldInline()
static bool shouldInline (ResolvedCall & resolvedCall) static
Returns true if the given call should be inlined.
Definition at line 355 of file Inliner.cpp.
Referenced by inlineCallsInSCC().
walkReferencedSymbolNodes()
static void walkReferencedSymbolNodes (Operation * op, CallGraph & cg, DenseMap< Attribute, CallGraphNode *> & resolvedRefs, function_ref< void(CallGraphNode *, Operation *)> callback) static
Walk all of the used symbol callgraph nodes referenced with the given op.
Definition at line 35 of file Inliner.cpp.
References mlir::SymbolOpInterface::canDiscardOnUseEmpty(), mlir::Operation::getBlock(), mlir::CallGraphNode::getCallableRegion(), mlir::Region::getOps(), mlir::Operation::getParentOp(), mlir::Region::getParentOp(), mlir::Operation::getRegion(), mlir::SymbolTable::getSymbolUses(), mlir::MemoryEffectOpInterface::hasNoEffect(), mlir::Operation::hasOneUse(), mlir::SymbolOpInterface::isPrivate(), mlir::SymbolTable::lookupNearestSymbolFrom(), mlir::CallGraph::lookupNode(), mlir::Operation::use_empty(), and mlir::SymbolTable::walkSymbolTables().