MLIR: lib/Conversion/LinalgToStandard/LinalgToStandard.cpp File Reference
LinalgToStandard.cpp File Reference
#include "mlir/Conversion/LinalgToStandard/LinalgToStandard.h"
#include "../PassDetail.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
Functions
template<typename LinalgOp >
static SmallVector< Type, 4 > extractOperandTypes (Operation *op)
Helper function to extract the operand types that are passed to the generated CallOp.
template<>
SmallVector< Type, 4 > extractOperandTypes< IndexedGenericOp > (Operation *op)
template<typename LinalgOp >
static FlatSymbolRefAttr getLibraryCallSymbolRef (Operation *op, PatternRewriter &rewriter)
Function Documentation
extractOperandTypes()
template<typename LinalgOp > static SmallVector<Type, 4> extractOperandTypes (Operation * op) static
Helper function to extract the operand types that are passed to the generated CallOp.
MemRefTypes have their layout canonicalized since the information is not used in signature generation. Note that static size information is not modified.
Definition at line 25 of file LinalgToStandard.cpp.
References mlir::eraseStridedLayout(), mlir::Operation::getNumOperands(), and mlir::Operation::getOperandTypes().
extractOperandTypes< IndexedGenericOp >()
template<> SmallVector<Type, 4> extractOperandTypes< IndexedGenericOp > (Operation * op)
Definition at line 41 of file LinalgToStandard.cpp.
References mlir::IndexType::get().
getLibraryCallSymbolRef()
template<typename LinalgOp > static FlatSymbolRefAttr getLibraryCallSymbolRef (Operation * op, PatternRewriter & rewriter) static
Definition at line 55 of file LinalgToStandard.cpp.
References mlir::PatternRewriter::create(), mlir::OpBuilder::create(), mlir::Operation::emitWarning(), mlir::eraseStridedLayout(), mlir::failure(), mlir::AffineMapAttr::get(), mlir::FunctionType::get(), mlir::UnitAttr::get(), mlir::Builder::getContext(), mlir::Operation::getContext(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerAttr(), mlir::Operation::getLoc(), mlir::Operation::getNumResults(), mlir::Operation::getParentOfType(), mlir::Builder::getSymbolRefAttr(), mlir::FlatSymbolRefAttr::getValue(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::OpState::setAttr(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().