MLIR: mlir::LLVM Namespace Reference
mlir::LLVM Namespace Reference
Namespaces
detail
Classes
class LLVMType
class ModuleTranslation
Implementation class for module translation.
Functions
Value createGlobalString (Location loc, OpBuilder &builder, StringRef name, StringRef value, LLVM::Linkage linkage, LLVM::LLVMDialect *llvmDialect)
Create an LLVM global containing the string "value" at the module containing surrounding the insertion point of builder.
bool satisfiesLLVMModule (Operation *op)
LLVM requires some operations to be inside of a Module operation.
std::unique_ptr< llvm::Module > cloneModuleIntoNewContext (llvm::LLVMContext *context, llvm::Module *module)
Clones the given module into the provided context.
void ensureDistinctSuccessors (Operation *op)
Make argument-taking successors of each block distinct.
std::unique_ptr< Pass > createLegalizeForExportPass ()
Creates a pass that legalizes the LLVM dialect operations so that they can be translated to LLVM IR.
Function Documentation
cloneModuleIntoNewContext()
std::unique_ptr< llvm::Module > mlir::LLVM::cloneModuleIntoNewContext (llvm::LLVMContext * context, llvm::Module * module)
Clones the given module into the provided context.
This is implemented by transforming the module into bitcode and then reparsing the bitcode in the provided context.
Definition at line 1984 of file LLVMDialect.cpp.
Referenced by mlir::ExecutionEngine::create().
createGlobalString()
Value mlir::LLVM::createGlobalString (Location loc, OpBuilder & builder, StringRef name, StringRef value, LLVM::Linkage linkage, LLVM::LLVMDialect * llvmDialect)
Create an LLVM global containing the string "value" at the module containing surrounding the insertion point of builder.
Obtain the address of that global and use it to compute the address of the first character in the string (operations inserted at the builder insertion point).
Definition at line 1949 of file LLVMDialect.cpp.
References mlir::OpBuilder::create(), mlir::LLVM::LLVMType::getArrayTy(), mlir::Builder::getIndexType(), mlir::OpBuilder::getInsertionBlock(), mlir::LLVM::LLVMType::getInt64Ty(), mlir::LLVM::LLVMType::getInt8PtrTy(), mlir::LLVM::LLVMType::getInt8Ty(), mlir::Builder::getIntegerAttr(), mlir::Operation::getParentOfType(), mlir::Block::getParentOp(), mlir::Builder::getStringAttr(), and mlir::LLVM::detail::LLVMDialectImpl::module.
createLegalizeForExportPass()
std::unique_ptr< Pass > mlir::LLVM::createLegalizeForExportPass ()
Creates a pass that legalizes the LLVM dialect operations so that they can be translated to LLVM IR.
Definition at line 68 of file LegalizeForExport.cpp.
ensureDistinctSuccessors()
void mlir::LLVM::ensureDistinctSuccessors (Operation * op)
Make argument-taking successors of each block distinct.
PHI nodes in LLVM IR use the predecessor ID to identify which value to take. They do not support different values coming from the same predecessor. If a block has another block as a successor more than once with different values, insert a new dummy block for LLVM PHI nodes to tell the sources apart.
Definition at line 51 of file LegalizeForExport.cpp.
References ensureDistinctSuccessors(), and mlir::Operation::walk().
Referenced by mlir::LLVM::ModuleTranslation::translateModule().
satisfiesLLVMModule()
bool mlir::LLVM::satisfiesLLVMModule (Operation * op)
LLVM requires some operations to be inside of a Module operation.
This function confirms that the Operation has the desired properties.
Definition at line 1978 of file LLVMDialect.cpp.
References mlir::Operation::hasTrait().
Referenced by mlir::LLVM::ModuleTranslation::ModuleTranslation(), parseReturnOp(), mlir::LLVM::ModuleTranslation::translateModule(), and verify().