MLIR: mlir::edsc::op Namespace Reference
mlir::edsc::op Namespace Reference
Functions
Value operator+ (Value lhs, Value rhs)
Value operator- (Value lhs, Value rhs)
Value operator* (Value lhs, Value rhs)
Value operator/ (Value lhs, Value rhs)
Value operator% (Value lhs, Value rhs)
Value floorDiv (Value lhs, Value rhs)
Value ceilDiv (Value lhs, Value rhs)
Value negate (Value value)
Logical operator overloadings.
Value operator && (Value lhs, Value rhs)
Value operator|| (Value lhs, Value rhs)
Value operator^ (Value lhs, Value rhs)
Value eq (Value lhs, Value rhs)
Comparison operator overloadings.
Value ne (Value lhs, Value rhs)
Value operator< (Value lhs, Value rhs)
Value operator<= (Value lhs, Value rhs)
Value operator> (Value lhs, Value rhs)
Value operator>= (Value lhs, Value rhs)
Function Documentation
ceilDiv()
Value mlir::edsc::op::ceilDiv (Value lhs, Value rhs)
Definition at line 265 of file Builders.cpp.
References mlir::AffineExpr::ceilDiv(), and createBinaryIndexHandle().
eq()
Value mlir::edsc::op::eq (Value lhs, Value rhs)
Comparison operator overloadings.
Definition at line 315 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::FlatAffineConstraints::addAffineForOpDomain(), addMemRefAccessConstraints(), addOrderingConstraints(), mlir::applyCmpPredicate(), computeDirectionVector(), mlir::edsc::TemplatedIndexedValue< Load, Store >::eq(), mlir::SDBM::get(), getAtomicOpScope(), mlir::FlatAffineConstraints::getConstantBoundOnDimSize(), getICmpPredicate(), mlir::FlatAffineConstraints::getInequality(), getLLVMCmpPredicate(), mlir::FlatAffineConstraints::getLowerAndUpperBound(), getNewNumDimsSymbols(), mlir::lowerAffineLowerBound(), mlir::edsc::TemplatedIndexedValue< Load, Store >::operator||(), specializeLoopForUnrolling(), mlir::LLVM::detail::vectorOneToOneRewrite(), mlir::SimpleAffineExprFlattener::visitConstantExpr(), mlir::SimpleAffineExprFlattener::visitDimExpr(), and mlir::SimpleAffineExprFlattener::visitSymbolExpr().
floorDiv()
Value mlir::edsc::op::floorDiv (Value lhs, Value rhs)
Definition at line 260 of file Builders.cpp.
References createBinaryIndexHandle(), and mlir::AffineExpr::floorDiv().
ne()
Value mlir::edsc::op::ne (Value lhs, Value rhs)
Definition at line 321 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::applyCmpPredicate(), getAtomicOpScope(), getICmpPredicate(), getLLVMCmpPredicate(), mlir::edsc::TemplatedIndexedValue< Load, Store >::ne(), and mlir::edsc::TemplatedIndexedValue< Load, Store >::operator||().
negate()
Value mlir::edsc::op::negate (Value value)
Logical operator overloadings.
Definition at line 270 of file Builders.cpp.
References mlir::Value::getType(), mlir::Type::isInteger(), and operator &&().
operator &&()
Value mlir::edsc::op::operator&& (Value lhs, Value rhs)
Referenced by negate(), and mlir::edsc::TemplatedIndexedValue< Load, Store >::operator^=().
operator%()
Value mlir::edsc::op::operator% (Value lhs, Value rhs)
Definition at line 255 of file Builders.cpp.
Referenced by mlir::edsc::TemplatedIndexedValue< Load, Store >::getElementalTypeAs(), and mlir::AffineExpr::operator!().
operator*()
Value mlir::edsc::op::operator* (Value lhs, Value rhs)
Definition at line 243 of file Builders.cpp.
operator+()
Value mlir::edsc::op::operator+ (Value lhs, Value rhs)
Definition at line 233 of file Builders.cpp.
operator-()
Value mlir::edsc::op::operator- (Value lhs, Value rhs)
Definition at line 238 of file Builders.cpp.
operator/()
Value mlir::edsc::op::operator/ (Value lhs, Value rhs)
Definition at line 248 of file Builders.cpp.
Referenced by mlir::edsc::TemplatedIndexedValue< Load, Store >::getElementalTypeAs().
operator<()
Value mlir::edsc::op::operator< (Value lhs, Value rhs)
Definition at line 327 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::tblgen::Dialect::Dialect().
operator<=()
Value mlir::edsc::op::operator<= (Value lhs, Value rhs)
Definition at line 335 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::Value::getType(), and mlir::Type::isa().
operator>()
Value mlir::edsc::op::operator> (Value lhs, Value rhs)
Definition at line 341 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::edsc::TemplatedIndexedValue< Load, Store >::operator||().
operator>=()
Value mlir::edsc::op::operator>= (Value lhs, Value rhs)
Definition at line 347 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::edsc::TemplatedIndexedValue< Load, Store >::operator||().
operator^()
Value mlir::edsc::op::operator^ (Value lhs, Value rhs)
Referenced by mlir::edsc::TemplatedIndexedValue< Load, Store >::getElementalTypeAs().
operator||()
Value mlir::edsc::op::operator|| (Value lhs, Value rhs)
Definition at line 281 of file Builders.cpp.
References mlir::Value::getType(), and mlir::Type::isInteger().
Referenced by mlir::edsc::TemplatedIndexedValue< Load, Store >::operator^=().