MLIR: mlir::edsc Namespace Reference
mlir::edsc Namespace Reference
Namespaces
intrinsics
op
ops
Classes
class AffineLoopNestBuilder
Deprecated.
class Append
class BlockBuilder
A BlockBuilder is a NestedBuilder for mlir::Block*.
class BlockHandle
A BlockHandle represents a (potentially "delayed") Block abstraction.
class BoundsCapture
Base class for MemRefBoundsCapture and VectorBoundsCapture.
class GenericLoopNestRangeBuilder
Helper template class for building scf.for and affine.loop nests from ranges.
class LoopBuilder
A LoopBuilder is a generic NestedBuilder for loop-like MLIR operations.
class LoopNestBuilder
Helper class to sugar building scf.for loop nests from ranges.
class MemRefBoundsCapture
A MemRefBoundsCapture represents the information required to step through a MemRef.
class NestedBuilder
A NestedBuilder is a scoping abstraction to create an idiomatic syntax embedded in C++ that serves the purpose of building nested MLIR.
struct OperationBuilder
class ParallelLoopNestBuilder
Helper class to sugar building scf.parallel loop nests from lower/upper bounds and step sizes.
class ScopedContext
Helper class to transparently handle builder insertion points by RAII.
struct StructuredIndexed
A StructuredIndexed represents an indexable quantity that is either:
class TemplatedIndexedValue
A TemplatedIndexedValue brings an index notation over the template Load and Store parameters.
struct ValueBuilder
class VectorBoundsCapture
A VectorBoundsCapture represents the information required to step through a Vector accessing each scalar element at a time.
Functions
LoopBuilder makeAffineLoopBuilder (Value *iv, ArrayRef< Value > lbs, ArrayRef< Value > ubs, int64_t step)
Constructs a new AffineForOp and captures the associated induction variable.
void affineLoopNestBuilder (ValueRange lbs, ValueRange ubs, ArrayRef< int64_t > steps, function_ref< void(ValueRange)> bodyBuilderFn=nullptr)
Creates a perfect nest of affine "for" loops, given the list of lower bounds, upper bounds and steps.
void affineLoopBuilder (ValueRange lbs, ValueRange ubs, int64_t step, function_ref< void(Value)> bodyBuilderFn=nullptr)
Creates a single affine "for" loop, iterating from max(lbs) to min(ubs) with the given step.
void defaultRegionBuilder (ArrayRef< BlockArgument > args)
Operation * makeGenericLinalgOp (ArrayRef< IteratorType > iteratorTypes, ArrayRef< StructuredIndexed > inputs, ArrayRef< StructuredIndexed > outputs, function_ref< void(ArrayRef< BlockArgument >)> regionBuilder=defaultRegionBuilder, ArrayRef< Value > otherValues={}, ArrayRef< Attribute > otherAttributes={})
Build a linalg.generic op with the specified inputs, outputs and region.
LoopBuilder makeParallelLoopBuilder (MutableArrayRef< Value > ivs, ArrayRef< Value > lbs, ArrayRef< Value > ubs, ArrayRef< Value > steps)
Constructs a new scf::ParallelOp and captures the associated induction variables.
LoopBuilder makeLoopBuilder (Value *iv, Value lb, Value ub, Value step, MutableArrayRef< Value > iterArgsHandles, ValueRange iterArgsInitValues)
Constructs a new scf::ForOp and captures the associated induction variable.
LoopBuilder makeLoopBuilder (Value *iv, Value lb, Value ub, Value step)
scf::ValueVector loopNestBuilder (ValueRange lbs, ValueRange ubs, ValueRange steps, function_ref< void(ValueRange)> fun=nullptr)
Adapters for building loop nests using the builder and the location stored in ScopedContext.
scf::ValueVector loopNestBuilder (Value lb, Value ub, Value step, function_ref< void(Value)> fun=nullptr)
scf::ValueVector loopNestBuilder (Value lb, Value ub, Value step, ValueRange iterArgInitValues, function_ref< scf::ValueVector(Value, ValueRange)> fun=nullptr)
ValueRange conditionBuilder (TypeRange results, Value condition, function_ref< scf::ValueVector()> thenBody, function_ref< scf::ValueVector()> elseBody=nullptr)
Adapters for building if conditions using the builder and the location stored in ScopedContext.
ValueRange conditionBuilder (Value condition, function_ref< void()> thenBody, function_ref< void()> elseBody=nullptr)
Function Documentation
affineLoopBuilder()
void mlir::edsc::affineLoopBuilder (ValueRange lbs, ValueRange ubs, int64_t step, function_ref< void(Value)> bodyBuilderFn = nullptr)
Creates a single affine "for" loop, iterating from max(lbs) to min(ubs) with the given step.
Uses the OpBuilder and Location stored in ScopedContext and assumes they are non-null. The optional "bodyBuilderFn" callback is called to construct the body of the loop and is passed the induction variable. The function is expected to use the builder and location stored in ScopedContext at the moment of the call. The function should not create the affine terminator op, which will be added regardless of the "bodyBuilderFn" being present.
Definition at line 118 of file Builders.cpp.
References mlir::OpBuilder::create(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), mlir::edsc::ScopedContext::getLocation(), and mlir::Builder::getMultiDimIdentityMap().
affineLoopNestBuilder()
void mlir::edsc::affineLoopNestBuilder (ValueRange lbs, ValueRange ubs, ArrayRef< int64_t > steps, function_ref< void(ValueRange)> bodyBuilderFn = nullptr)
Creates a perfect nest of affine "for" loops, given the list of lower bounds, upper bounds and steps.
The three lists are expected to contain the same number of elements. Uses the OpBuilder and Location stored in ScopedContext and assumes they are non-null. The optional "bodyBuilderFn" callback is called to construct the body of the innermost loop and is passed the list of loop induction variables, in order from outermost to innermost. The function is expected to use the builder and location stored in ScopedContext at the moment of the call. The function should not create the affine terminator op, which will be added regardless of the "bodyBuilderFn" being present.
Definition at line 67 of file Builders.cpp.
References mlir::OpBuilder::create(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), mlir::Builder::getDimIdentityMap(), mlir::edsc::ScopedContext::getLocation(), mlir::ConstantIndexOp::getValue(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by mlir::linalg::GenerateLoopNest< LoopTy >::doit().
conditionBuilder() [1/2]
ValueRange mlir::edsc::conditionBuilder (TypeRange results, Value condition, function_ref< scf::ValueVector()> thenBody, function_ref< scf::ValueVector()> elseBody = nullptr)
Adapters for building if conditions using the builder and the location stored in ScopedContext.
'thenBody' is mandatory, 'elseBody' can be omitted if the condition should not have an 'else' part.
Definition at line 176 of file Builders.cpp.
References mlir::OpBuilder::create(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), mlir::edsc::ScopedContext::getLocation(), and wrapIfBody().
conditionBuilder() [2/2]
ValueRange mlir::edsc::conditionBuilder (Value condition, function_ref< void()> thenBody, function_ref< void()> elseBody = nullptr)
Definition at line 197 of file Builders.cpp.
References mlir::OpBuilder::create(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), mlir::edsc::ScopedContext::getLocation(), and wrapZeroResultIfBody().
defaultRegionBuilder()
void mlir::edsc::defaultRegionBuilder (ArrayRef< BlockArgument > args) inline
Definition at line 58 of file Builders.h.
References makeGenericLinalgOp().
loopNestBuilder() [1/3]
mlir::scf::ValueVector mlir::edsc::loopNestBuilder (ValueRange lbs, ValueRange ubs, ValueRange steps, function_ref< void(ValueRange)> fun = nullptr)
Adapters for building loop nests using the builder and the location stored in ScopedContext.
Actual builders are in scf::buildLoopNest.
Definition at line 117 of file Builders.cpp.
References mlir::scf::buildLoopNest(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), and mlir::edsc::ScopedContext::getLocation().
Referenced by mlir::linalg::GenerateLoopNest< LoopTy >::doit(), mlir::linalg::generateParallelLoopNest(), insertCopyLoops(), loopNestBuilder(), and mlir::VectorTransferRewriter< TransferOpTy >::matchAndRewrite().
loopNestBuilder() [2/3]
mlir::scf::ValueVector mlir::edsc::loopNestBuilder (Value lb, Value ub, Value step, function_ref< void(Value)> fun = nullptr)
Definition at line 132 of file Builders.cpp.
References loopNestBuilder().
loopNestBuilder() [3/3]
mlir::scf::ValueVector mlir::edsc::loopNestBuilder (Value lb, Value ub, Value step, ValueRange iterArgInitValues, function_ref< scf::ValueVector(Value, ValueRange)> fun = nullptr)
Definition at line 144 of file Builders.cpp.
References mlir::scf::buildLoopNest(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), and mlir::edsc::ScopedContext::getLocation().
makeAffineLoopBuilder()
LoopBuilder mlir::edsc::makeAffineLoopBuilder (Value * iv, ArrayRef< Value > lbs, ArrayRef< Value > ubs, int64_t step)
Constructs a new AffineForOp and captures the associated induction variable.
A Value pointer is passed as the first argument and is the only way to capture the loop induction variable.
Definition at line 37 of file Builders.cpp.
References mlir::OpBuilder::create(), emitStaticFor(), mlir::edsc::NestedBuilder::enter(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::getForInductionVarOwner(), mlir::edsc::ScopedContext::getLocation(), and mlir::Builder::getMultiDimIdentityMap().
Referenced by mlir::edsc::AffineLoopNestBuilder::AffineLoopNestBuilder(), and mlir::edsc::LoopBuilder::getOp().
makeGenericLinalgOp()
Operation * mlir::edsc::makeGenericLinalgOp (ArrayRef< IteratorType > iteratorTypes, ArrayRef< StructuredIndexed > inputs, ArrayRef< StructuredIndexed > outputs, function_ref< void(ArrayRef< BlockArgument >)> regionBuilder = defaultRegionBuilder, ArrayRef< Value > otherValues = {}, ArrayRef< Attribute > otherAttributes = {})
Build a linalg.generic op with the specified inputs, outputs and region.
otherValues and otherAttributes may be passed and will be appended as operands and attributes respectively.
Prerequisites:
inputs may contain StructuredIndexed that capture either buffer or tensor values.
outputs may contain StructuredIndexed that capture either buffer values or tensor types. If both buffer values and tensor types are present, then all buffer values must appear before any tensor type. Without this restriction output tensor results would need to be reordered, which would result in surprising behavior when combined with region definition.
Definition at line 73 of file Builders.cpp.
References mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::IntegerType::get(), mlir::IntegerAttr::get(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::getElementTypeOrSelf(), mlir::edsc::ScopedContext::getLocation(), mlir::AffineMap::inferFromExprList(), and mlir::toString().
Referenced by defaultRegionBuilder(), mlir::edsc::ops::linalg_generic_conv_nhwc(), mlir::edsc::ops::linalg_generic_dilated_conv_nhwc(), mlir::edsc::ops::linalg_generic_matmul(), and mlir::edsc::ops::linalg_generic_pointwise().
makeLoopBuilder() [1/2]
mlir::edsc::LoopBuilder mlir::edsc::makeLoopBuilder (Value * iv, Value lb, Value ub, Value step, MutableArrayRef< Value > iterArgsHandles, ValueRange iterArgsInitValues)
Constructs a new scf::ForOp and captures the associated induction variable.
A Value pointer is passed as the first argument and is the only way to capture the loop induction variable.
Definition at line 99 of file Builders.cpp.
References mlir::edsc::NestedBuilder::enter(), mlir::scf::getForInductionVarOwner(), and mlir::edsc::LoopBuilder::setOp().
Referenced by mlir::edsc::LoopBuilder::getOp(), mlir::edsc::LoopNestBuilder::LoopNestBuilder(), and makeLoopBuilder().
makeLoopBuilder() [2/2]
LoopBuilder mlir::edsc::makeLoopBuilder (Value * iv, Value lb, Value ub, Value step) inline
Definition at line 40 of file Builders.h.
References makeLoopBuilder().
makeParallelLoopBuilder()
LoopBuilder mlir::edsc::makeParallelLoopBuilder (MutableArrayRef< Value > ivs, ArrayRef< Value > lbs, ArrayRef< Value > ubs, ArrayRef< Value > steps)
Constructs a new scf::ParallelOp and captures the associated induction variables.
An array of Value pointers is passed as the first argument and is the only way to capture loop induction variables.
Definition at line 83 of file Builders.cpp.
References mlir::edsc::NestedBuilder::enter().
Referenced by mlir::edsc::LoopBuilder::getOp(), and mlir::edsc::ParallelLoopNestBuilder::ParallelLoopNestBuilder().