MLIR: mlir::edsc::intrinsics Namespace Reference
mlir::edsc::intrinsics Namespace Reference
Classes
struct FoldedValueBuilder
Typedefs
using affine_apply = ValueBuilder< AffineApplyOp >
using affine_if = OperationBuilder< AffineIfOp >
using affine_load = ValueBuilder< AffineLoadOp >
using affine_min = ValueBuilder< AffineMinOp >
using affine_max = ValueBuilder< AffineMaxOp >
using affine_store = OperationBuilder< AffineStoreOp >
using AffineIndexedValue = TemplatedIndexedValue< affine_load, affine_store >
Provide an index notation around affine_load and affine_store.
using folded_std_constant_index = FoldedValueBuilder< ConstantIndexOp >
using folded_std_constant_float = FoldedValueBuilder< ConstantFloatOp >
using folded_std_constant_int = FoldedValueBuilder< ConstantIntOp >
using folded_std_constant = FoldedValueBuilder< ConstantOp >
using folded_std_dim = FoldedValueBuilder< DimOp >
using folded_std_muli = FoldedValueBuilder< MulIOp >
using folded_std_addi = FoldedValueBuilder< AddIOp >
using folded_std_addf = FoldedValueBuilder< AddFOp >
using folded_std_alloc = FoldedValueBuilder< AllocOp >
using folded_std_extract_element = FoldedValueBuilder< ExtractElementOp >
using folded_std_index_cast = FoldedValueBuilder< IndexCastOp >
using folded_std_mulf = FoldedValueBuilder< MulFOp >
using folded_std_memref_cast = FoldedValueBuilder< MemRefCastOp >
using folded_std_select = FoldedValueBuilder< SelectOp >
using folded_std_load = FoldedValueBuilder< LoadOp >
using folded_std_subi = FoldedValueBuilder< SubIOp >
using folded_std_sub_view = FoldedValueBuilder< SubViewOp >
using folded_std_tanh = FoldedValueBuilder< TanhOp >
using folded_std_tensor_load = FoldedValueBuilder< TensorLoadOp >
using folded_std_view = FoldedValueBuilder< ViewOp >
using folded_std_zero_extendi = FoldedValueBuilder< ZeroExtendIOp >
using folded_std_sign_extendi = FoldedValueBuilder< SignExtendIOp >
using linalg_copy = OperationBuilder< linalg::CopyOp >
using linalg_dot = OperationBuilder< linalg::DotOp >
using linalg_fill = OperationBuilder< linalg::FillOp >
using linalg_matmul = OperationBuilder< linalg::MatmulOp >
using linalg_matvec = OperationBuilder< linalg::MatvecOp >
using linalg_range = ValueBuilder< linalg::RangeOp >
using linalg_reshape = ValueBuilder< linalg::ReshapeOp >
using linalg_slice = ValueBuilder< linalg::SliceOp >
using linalg_yield = OperationBuilder< linalg::YieldOp >
using loop_yield = OperationBuilder< scf::YieldOp >
using std_addi = ValueBuilder< AddIOp >
using std_addf = ValueBuilder< AddFOp >
using std_alloc = ValueBuilder< AllocOp >
using std_alloca = ValueBuilder< AllocaOp >
using std_call = OperationBuilder< CallOp >
using std_create_complex = ValueBuilder< CreateComplexOp >
using std_constant = ValueBuilder< ConstantOp >
using std_constant_float = ValueBuilder< ConstantFloatOp >
using std_constant_index = ValueBuilder< ConstantIndexOp >
using std_constant_int = ValueBuilder< ConstantIntOp >
using std_dealloc = OperationBuilder< DeallocOp >
using std_dim = ValueBuilder< DimOp >
using std_extract_element = ValueBuilder< ExtractElementOp >
using std_im = ValueBuilder< ImOp >
using std_index_cast = ValueBuilder< IndexCastOp >
using std_muli = ValueBuilder< MulIOp >
using std_mulf = ValueBuilder< MulFOp >
using std_memref_cast = ValueBuilder< MemRefCastOp >
using std_re = ValueBuilder< ReOp >
using std_ret = OperationBuilder< ReturnOp >
using std_select = ValueBuilder< SelectOp >
using std_load = ValueBuilder< LoadOp >
using std_splat = ValueBuilder< SplatOp >
using std_store = OperationBuilder< StoreOp >
using std_subi = ValueBuilder< SubIOp >
using std_sub_view = ValueBuilder< SubViewOp >
using std_tanh = ValueBuilder< TanhOp >
using std_tensor_load = ValueBuilder< TensorLoadOp >
using std_tensor_store = OperationBuilder< TensorStoreOp >
using std_view = ValueBuilder< ViewOp >
using std_zero_extendi = ValueBuilder< ZeroExtendIOp >
using std_sign_extendi = ValueBuilder< SignExtendIOp >
using StdIndexedValue = TemplatedIndexedValue< intrinsics::std_load, intrinsics::std_store >
Provide an index notation around sdt_load and std_store.
using vector_broadcast = ValueBuilder< vector::BroadcastOp >
using vector_contract = ValueBuilder< vector::ContractionOp >
using vector_insert = ValueBuilder< vector::InsertOp >
using vector_fma = ValueBuilder< vector::FMAOp >
using vector_extract = ValueBuilder< vector::ExtractOp >
using vector_matmul = ValueBuilder< vector::MatmulOp >
using vector_outerproduct = ValueBuilder< vector::OuterProductOp >
using vector_print = OperationBuilder< vector::PrintOp >
using vector_transfer_read = ValueBuilder< vector::TransferReadOp >
using vector_transfer_write = OperationBuilder< vector::TransferWriteOp >
using vector_transpose = ValueBuilder< vector::TransposeOp >
using vector_type_cast = ValueBuilder< vector::TypeCastOp >
Functions
BranchOp std_br (BlockHandle bh, ValueRange operands)
Branches into the mlir::Block* captured by BlockHandle b with operands.
BranchOp std_br (BlockHandle *bh, ArrayRef< Type > types, MutableArrayRef< Value > captures, ValueRange operands)
Creates a new mlir::Block* and branches to it from the current block.
CondBranchOp std_cond_br (Value cond, BlockHandle trueBranch, ValueRange trueOperands, BlockHandle falseBranch, ValueRange falseOperands)
Branches into the mlir::Block* captured by BlockHandle trueBranch with trueOperands if cond evaluates to true (resp.
CondBranchOp std_cond_br (Value cond, BlockHandle *trueBranch, ArrayRef< Type > trueTypes, MutableArrayRef< Value > trueCaptures, ValueRange trueOperands, BlockHandle *falseBranch, ArrayRef< Type > falseTypes, MutableArrayRef< Value > falseCaptures, ValueRange falseOperands)
Eagerly creates new mlir::Block* with argument types specified by trueOperands/falseOperands.
Typedef Documentation
affine_apply
using mlir::edsc::intrinsics::affine_apply = typedef ValueBuilder<AffineApplyOp>
Definition at line 17 of file Intrinsics.h.
affine_if
using mlir::edsc::intrinsics::affine_if = typedef OperationBuilder<AffineIfOp>
Definition at line 18 of file Intrinsics.h.
affine_load
using mlir::edsc::intrinsics::affine_load = typedef ValueBuilder<AffineLoadOp>
Definition at line 19 of file Intrinsics.h.
affine_max
using mlir::edsc::intrinsics::affine_max = typedef ValueBuilder<AffineMaxOp>
Definition at line 21 of file Intrinsics.h.
affine_min
using mlir::edsc::intrinsics::affine_min = typedef ValueBuilder<AffineMinOp>
Definition at line 20 of file Intrinsics.h.
affine_store
using mlir::edsc::intrinsics::affine_store = typedef OperationBuilder<AffineStoreOp>
Definition at line 22 of file Intrinsics.h.
AffineIndexedValue
using mlir::edsc::intrinsics::AffineIndexedValue = typedef TemplatedIndexedValue<affine_load, affine_store>
Provide an index notation around affine_load and affine_store.
Definition at line 25 of file Intrinsics.h.
folded_std_addf
using mlir::edsc::intrinsics::folded_std_addf = typedef FoldedValueBuilder<AddFOp>
Definition at line 42 of file FoldedIntrinsics.h.
folded_std_addi
using mlir::edsc::intrinsics::folded_std_addi = typedef FoldedValueBuilder<AddIOp>
Definition at line 41 of file FoldedIntrinsics.h.
folded_std_alloc
using mlir::edsc::intrinsics::folded_std_alloc = typedef FoldedValueBuilder<AllocOp>
Definition at line 43 of file FoldedIntrinsics.h.
folded_std_constant
typedef FoldedValueBuilder< ConstantOp > mlir::edsc::intrinsics::folded_std_constant
Definition at line 38 of file FoldedIntrinsics.h.
folded_std_constant_float
typedef FoldedValueBuilder< ConstantFloatOp > mlir::edsc::intrinsics::folded_std_constant_float
Definition at line 36 of file FoldedIntrinsics.h.
folded_std_constant_index
typedef FoldedValueBuilder< ConstantIndexOp > mlir::edsc::intrinsics::folded_std_constant_index
Definition at line 35 of file FoldedIntrinsics.h.
folded_std_constant_int
typedef FoldedValueBuilder< ConstantIntOp > mlir::edsc::intrinsics::folded_std_constant_int
Definition at line 37 of file FoldedIntrinsics.h.
folded_std_dim
typedef FoldedValueBuilder< DimOp > mlir::edsc::intrinsics::folded_std_dim
Definition at line 39 of file FoldedIntrinsics.h.
folded_std_extract_element
using mlir::edsc::intrinsics::folded_std_extract_element = typedef FoldedValueBuilder<ExtractElementOp>
Definition at line 49 of file FoldedIntrinsics.h.
folded_std_index_cast
using mlir::edsc::intrinsics::folded_std_index_cast = typedef FoldedValueBuilder<IndexCastOp>
Definition at line 50 of file FoldedIntrinsics.h.
folded_std_load
using mlir::edsc::intrinsics::folded_std_load = typedef FoldedValueBuilder<LoadOp>
Definition at line 55 of file FoldedIntrinsics.h.
folded_std_memref_cast
using mlir::edsc::intrinsics::folded_std_memref_cast = typedef FoldedValueBuilder<MemRefCastOp>
Definition at line 53 of file FoldedIntrinsics.h.
folded_std_mulf
using mlir::edsc::intrinsics::folded_std_mulf = typedef FoldedValueBuilder<MulFOp>
Definition at line 52 of file FoldedIntrinsics.h.
folded_std_muli
typedef FoldedValueBuilder< MulIOp > mlir::edsc::intrinsics::folded_std_muli
Definition at line 40 of file FoldedIntrinsics.h.
folded_std_select
using mlir::edsc::intrinsics::folded_std_select = typedef FoldedValueBuilder<SelectOp>
Definition at line 54 of file FoldedIntrinsics.h.
folded_std_sign_extendi
using mlir::edsc::intrinsics::folded_std_sign_extendi = typedef FoldedValueBuilder<SignExtendIOp>
Definition at line 62 of file FoldedIntrinsics.h.
folded_std_sub_view
using mlir::edsc::intrinsics::folded_std_sub_view = typedef FoldedValueBuilder<SubViewOp>
Definition at line 57 of file FoldedIntrinsics.h.
folded_std_subi
using mlir::edsc::intrinsics::folded_std_subi = typedef FoldedValueBuilder<SubIOp>
Definition at line 56 of file FoldedIntrinsics.h.
folded_std_tanh
using mlir::edsc::intrinsics::folded_std_tanh = typedef FoldedValueBuilder<TanhOp>
Definition at line 58 of file FoldedIntrinsics.h.
folded_std_tensor_load
using mlir::edsc::intrinsics::folded_std_tensor_load = typedef FoldedValueBuilder<TensorLoadOp>
Definition at line 59 of file FoldedIntrinsics.h.
folded_std_view
using mlir::edsc::intrinsics::folded_std_view = typedef FoldedValueBuilder<ViewOp>
Definition at line 60 of file FoldedIntrinsics.h.
folded_std_zero_extendi
using mlir::edsc::intrinsics::folded_std_zero_extendi = typedef FoldedValueBuilder<ZeroExtendIOp>
Definition at line 61 of file FoldedIntrinsics.h.
linalg_copy
using mlir::edsc::intrinsics::linalg_copy = typedef OperationBuilder<linalg::CopyOp>
Definition at line 18 of file Intrinsics.h.
linalg_dot
using mlir::edsc::intrinsics::linalg_dot = typedef OperationBuilder<linalg::DotOp>
Definition at line 19 of file Intrinsics.h.
linalg_fill
using mlir::edsc::intrinsics::linalg_fill = typedef OperationBuilder<linalg::FillOp>
Definition at line 20 of file Intrinsics.h.
linalg_matmul
using mlir::edsc::intrinsics::linalg_matmul = typedef OperationBuilder<linalg::MatmulOp>
Definition at line 21 of file Intrinsics.h.
linalg_matvec
using mlir::edsc::intrinsics::linalg_matvec = typedef OperationBuilder<linalg::MatvecOp>
Definition at line 22 of file Intrinsics.h.
linalg_range
using mlir::edsc::intrinsics::linalg_range = typedef ValueBuilder<linalg::RangeOp>
Definition at line 23 of file Intrinsics.h.
linalg_reshape
using mlir::edsc::intrinsics::linalg_reshape = typedef ValueBuilder<linalg::ReshapeOp>
Definition at line 24 of file Intrinsics.h.
linalg_slice
using mlir::edsc::intrinsics::linalg_slice = typedef ValueBuilder<linalg::SliceOp>
Definition at line 25 of file Intrinsics.h.
linalg_yield
using mlir::edsc::intrinsics::linalg_yield = typedef OperationBuilder<linalg::YieldOp>
Definition at line 26 of file Intrinsics.h.
loop_yield
using mlir::edsc::intrinsics::loop_yield = typedef OperationBuilder<scf::YieldOp>
Definition at line 18 of file Intrinsics.h.
std_addf
using mlir::edsc::intrinsics::std_addf = typedef ValueBuilder<AddFOp>
Definition at line 18 of file Intrinsics.h.
std_addi
using mlir::edsc::intrinsics::std_addi = typedef ValueBuilder<AddIOp>
Definition at line 17 of file Intrinsics.h.
std_alloc
using mlir::edsc::intrinsics::std_alloc = typedef ValueBuilder<AllocOp>
Definition at line 19 of file Intrinsics.h.
std_alloca
using mlir::edsc::intrinsics::std_alloca = typedef ValueBuilder<AllocaOp>
Definition at line 20 of file Intrinsics.h.
std_call
using mlir::edsc::intrinsics::std_call = typedef OperationBuilder<CallOp>
Definition at line 21 of file Intrinsics.h.
std_constant
using mlir::edsc::intrinsics::std_constant = typedef ValueBuilder<ConstantOp>
Definition at line 23 of file Intrinsics.h.
std_constant_float
using mlir::edsc::intrinsics::std_constant_float = typedef ValueBuilder<ConstantFloatOp>
Definition at line 24 of file Intrinsics.h.
std_constant_index
using mlir::edsc::intrinsics::std_constant_index = typedef ValueBuilder<ConstantIndexOp>
Definition at line 25 of file Intrinsics.h.
std_constant_int
using mlir::edsc::intrinsics::std_constant_int = typedef ValueBuilder<ConstantIntOp>
Definition at line 26 of file Intrinsics.h.
std_create_complex
using mlir::edsc::intrinsics::std_create_complex = typedef ValueBuilder<CreateComplexOp>
Definition at line 22 of file Intrinsics.h.
std_dealloc
using mlir::edsc::intrinsics::std_dealloc = typedef OperationBuilder<DeallocOp>
Definition at line 27 of file Intrinsics.h.
std_dim
using mlir::edsc::intrinsics::std_dim = typedef ValueBuilder<DimOp>
Definition at line 28 of file Intrinsics.h.
std_extract_element
using mlir::edsc::intrinsics::std_extract_element = typedef ValueBuilder<ExtractElementOp>
Definition at line 29 of file Intrinsics.h.
std_im
using mlir::edsc::intrinsics::std_im = typedef ValueBuilder<ImOp>
Definition at line 30 of file Intrinsics.h.
std_index_cast
using mlir::edsc::intrinsics::std_index_cast = typedef ValueBuilder<IndexCastOp>
Definition at line 31 of file Intrinsics.h.
std_load
using mlir::edsc::intrinsics::std_load = typedef ValueBuilder<LoadOp>
Definition at line 38 of file Intrinsics.h.
std_memref_cast
using mlir::edsc::intrinsics::std_memref_cast = typedef ValueBuilder<MemRefCastOp>
Definition at line 34 of file Intrinsics.h.
std_mulf
using mlir::edsc::intrinsics::std_mulf = typedef ValueBuilder<MulFOp>
Definition at line 33 of file Intrinsics.h.
std_muli
using mlir::edsc::intrinsics::std_muli = typedef ValueBuilder<MulIOp>
Definition at line 32 of file Intrinsics.h.
std_re
using mlir::edsc::intrinsics::std_re = typedef ValueBuilder<ReOp>
Definition at line 35 of file Intrinsics.h.
std_ret
using mlir::edsc::intrinsics::std_ret = typedef OperationBuilder<ReturnOp>
Definition at line 36 of file Intrinsics.h.
std_select
using mlir::edsc::intrinsics::std_select = typedef ValueBuilder<SelectOp>
Definition at line 37 of file Intrinsics.h.
std_sign_extendi
using mlir::edsc::intrinsics::std_sign_extendi = typedef ValueBuilder<SignExtendIOp>
Definition at line 48 of file Intrinsics.h.
std_splat
using mlir::edsc::intrinsics::std_splat = typedef ValueBuilder<SplatOp>
Definition at line 39 of file Intrinsics.h.
std_store
using mlir::edsc::intrinsics::std_store = typedef OperationBuilder<StoreOp>
Definition at line 40 of file Intrinsics.h.
std_sub_view
using mlir::edsc::intrinsics::std_sub_view = typedef ValueBuilder<SubViewOp>
Definition at line 42 of file Intrinsics.h.
std_subi
using mlir::edsc::intrinsics::std_subi = typedef ValueBuilder<SubIOp>
Definition at line 41 of file Intrinsics.h.
std_tanh
using mlir::edsc::intrinsics::std_tanh = typedef ValueBuilder<TanhOp>
Definition at line 43 of file Intrinsics.h.
std_tensor_load
using mlir::edsc::intrinsics::std_tensor_load = typedef ValueBuilder<TensorLoadOp>
Definition at line 44 of file Intrinsics.h.
std_tensor_store
using mlir::edsc::intrinsics::std_tensor_store = typedef OperationBuilder<TensorStoreOp>
Definition at line 45 of file Intrinsics.h.
std_view
using mlir::edsc::intrinsics::std_view = typedef ValueBuilder<ViewOp>
Definition at line 46 of file Intrinsics.h.
std_zero_extendi
using mlir::edsc::intrinsics::std_zero_extendi = typedef ValueBuilder<ZeroExtendIOp>
Definition at line 47 of file Intrinsics.h.
StdIndexedValue
using mlir::edsc::intrinsics::StdIndexedValue = typedef TemplatedIndexedValue<intrinsics::std_load, intrinsics::std_store>
Provide an index notation around sdt_load and std_store.
Definition at line 106 of file Intrinsics.h.
vector_broadcast
using mlir::edsc::intrinsics::vector_broadcast = typedef ValueBuilder<vector::BroadcastOp>
Definition at line 17 of file Intrinsics.h.
vector_contract
using mlir::edsc::intrinsics::vector_contract = typedef ValueBuilder<vector::ContractionOp>
Definition at line 18 of file Intrinsics.h.
vector_extract
typedef ValueBuilder< vector::ExtractOp > mlir::edsc::intrinsics::vector_extract
Definition at line 21 of file Intrinsics.h.
vector_fma
typedef ValueBuilder< vector::FMAOp > mlir::edsc::intrinsics::vector_fma
Definition at line 20 of file Intrinsics.h.
vector_insert
typedef ValueBuilder< vector::InsertOp > mlir::edsc::intrinsics::vector_insert
Definition at line 19 of file Intrinsics.h.
vector_matmul
using mlir::edsc::intrinsics::vector_matmul = typedef ValueBuilder<vector::MatmulOp>
Definition at line 22 of file Intrinsics.h.
vector_outerproduct
using mlir::edsc::intrinsics::vector_outerproduct = typedef ValueBuilder<vector::OuterProductOp>
Definition at line 23 of file Intrinsics.h.
vector_print
using mlir::edsc::intrinsics::vector_print = typedef OperationBuilder<vector::PrintOp>
Definition at line 24 of file Intrinsics.h.
vector_transfer_read
using mlir::edsc::intrinsics::vector_transfer_read = typedef ValueBuilder<vector::TransferReadOp>
Definition at line 25 of file Intrinsics.h.
vector_transfer_write
using mlir::edsc::intrinsics::vector_transfer_write = typedef OperationBuilder<vector::TransferWriteOp>
Definition at line 26 of file Intrinsics.h.
vector_transpose
using mlir::edsc::intrinsics::vector_transpose = typedef ValueBuilder<vector::TransposeOp>
Definition at line 27 of file Intrinsics.h.
vector_type_cast
using mlir::edsc::intrinsics::vector_type_cast = typedef ValueBuilder<vector::TypeCastOp>
Definition at line 28 of file Intrinsics.h.
Function Documentation
std_br() [1/2]
BranchOp mlir::edsc::intrinsics::std_br (BlockHandle bh, ValueRange operands)
Branches into the mlir::Block* captured by BlockHandle b with operands.
Prerequisites: All Handles have already captured previously constructed IR objects.
Definition at line 15 of file Intrinsics.cpp.
References mlir::edsc::BlockHandle::getBlock().
std_br() [2/2]
BranchOp mlir::edsc::intrinsics::std_br (BlockHandle * bh, ArrayRef< Type > types, MutableArrayRef< Value > captures, ValueRange operands)
Creates a new mlir::Block* and branches to it from the current block.
Argument types are specified by operands. Captures the new block in bh and the actual operands in captures. To insert the new mlir::Block*, a local ScopedContext is constructed and released to the current block. The branch operation is then added to the new block.
Prerequisites: b has not yet captured an mlir::Block*. No captures have captured any mlir::Value. All operands have already captured an mlir::Value captures.size() == operands.size() captures and operands are pairwise of the same type.
Definition at line 21 of file Intrinsics.cpp.
References mlir::edsc::BlockHandle::getBlock().
std_cond_br() [1/2]
CondBranchOp mlir::edsc::intrinsics::std_cond_br (Value cond, BlockHandle trueBranch, ValueRange trueOperands, BlockHandle falseBranch, ValueRange falseOperands)
Branches into the mlir::Block* captured by BlockHandle trueBranch with trueOperands if cond evaluates to true (resp.
falseBranch and falseOperand if cond evaluates to false).
Prerequisites: All Handles have captured previously constructed IR objects.
Definition at line 30 of file Intrinsics.cpp.
References mlir::edsc::BlockHandle::getBlock().
std_cond_br() [2/2]
CondBranchOp mlir::edsc::intrinsics::std_cond_br (Value cond, BlockHandle * trueBranch, ArrayRef< Type > trueTypes, MutableArrayRef< Value > trueCaptures, ValueRange trueOperands, BlockHandle * falseBranch, ArrayRef< Type > falseTypes, MutableArrayRef< Value > falseCaptures, ValueRange falseOperands)
Eagerly creates new mlir::Block* with argument types specified by trueOperands/falseOperands.
Captures the new blocks in trueBranch/falseBranch and the arguments in trueCaptures/falseCaptures. To insert the new mlir::Block*, a local ScopedContext is constructed and released. The branch operation is then added in the original location and targeting the eagerly constructed blocks.
Prerequisites: trueBranch/falseBranch has not yet captured an mlir::Block*. No trueCaptures/falseCaptures have captured any mlir::Value. All trueOperands/trueOperands have already captured an mlir::Value trueCaptures.size() == trueOperands.size() falseCaptures.size() == falseOperands.size() trueCaptures and trueOperands are pairwise of the same type falseCaptures and falseOperands are pairwise of the same type.
Definition at line 41 of file Intrinsics.cpp.
References mlir::edsc::BlockHandle::getBlock().