MLIR: mlir::LLVM::detail Namespace Reference
mlir::LLVM::detail Namespace Reference
Classes
class DebugTranslation
struct LLVMDialectImpl
struct LLVMTypeStorage
Functions
LogicalResult oneToOneRewrite (Operation *op, StringRef targetOp, ValueRange operands, LLVMTypeConverter &typeConverter, ConversionPatternRewriter &rewriter)
Replaces the given operation "op" with a new operation of type "targetOp" and given operands.
LogicalResult vectorOneToOneRewrite (Operation *op, StringRef targetOp, ValueRange operands, LLVMTypeConverter &typeConverter, ConversionPatternRewriter &rewriter)
Function Documentation
oneToOneRewrite()
LogicalResult mlir::LLVM::detail::oneToOneRewrite (Operation * op, StringRef targetOp, ValueRange operands, LLVMTypeConverter & typeConverter, ConversionPatternRewriter & rewriter)
Replaces the given operation "op" with a new operation of type "targetOp" and given operands.
Definition at line 1211 of file StandardToLLVM.cpp.
References mlir::OperationState::addTypes(), mlir::TypeConverter::convertType(), mlir::PatternRewriter::create(), mlir::OpBuilder::createOperation(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failure(), mlir::Operation::getAttrs(), mlir::Builder::getI64ArrayAttr(), mlir::Operation::getLoc(), mlir::Operation::getNumResults(), mlir::Operation::getResult(), mlir::Operation::getResultTypes(), mlir::Value::getType(), mlir::LLVMTypeConverter::packFunctionResults(), mlir::ConversionPatternRewriter::replaceOp(), and mlir::success().
Referenced by mlir::OneToOneConvertToLLVMPattern< SourceOp, TargetOp >::matchAndRewrite(), and vectorOneToOneRewrite().
vectorOneToOneRewrite()
LogicalResult mlir::LLVM::detail::vectorOneToOneRewrite (Operation * op, StringRef targetOp, ValueRange operands, LLVMTypeConverter & typeConverter, ConversionPatternRewriter & rewriter)
Definition at line 1279 of file StandardToLLVM.cpp.
References mlir::OperationState::addTypes(), mlir::MemRefDescriptor::alignedPtr(), mlir::Location::cast(), mlir::Type::cast(), mlir::TypeConverter::convertType(), mlir::ModuleOp::create(), mlir::PatternRewriter::create(), mlir::OpBuilder::create(), createIndexAttrConstant(), mlir::OpBuilder::createOperation(), mlir::Operation::emitWarning(), mlir::detail::enumerate(), mlir::edsc::op::eq(), mlir::ConversionPatternRewriter::eraseOp(), extractNDVectorTypeInfo(), mlir::failed(), mlir::failure(), mlir::VectorType::get(), mlir::DenseElementsAttr::get(), mlir::MemRefType::getAffineMaps(), mlir::Operation::getAttrs(), mlir::ModuleOp::getBodyRegion(), mlir::MemRefType::getDynamicStrideOrOffset(), getElementPtrType(), mlir::getElementTypeOrSelf(), mlir::Builder::getFloatAttr(), mlir::LLVM::LLVMType::getFunctionTy(), mlir::Builder::getI32ArrayAttr(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getI64IntegerAttr(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerType(), mlir::Operation::getLoc(), mlir::Value::getLoc(), mlir::MemRefType::getMemorySpace(), getMemRefEltSizeInBytes(), mlir::Operation::getNumOperands(), mlir::Operation::getOperands(), mlir::Operation::getOperandTypes(), mlir::Operation::getParentOfType(), mlir::Operation::getResult(), mlir::Operation::getResults(), mlir::MemRefType::getShape(), mlir::getStridesAndOffset(), mlir::Builder::getSymbolRefAttr(), mlir::Value::getType(), mlir::ValueRange::getType(), mlir::ValueRange::getTypes(), mlir::LLVM::LLVMType::getUnderlyingType(), mlir::Builder::getUnknownLoc(), mlir::Builder::getZeroAttr(), handleMultidimensionalVectors(), mlir::Type::isa(), mlir::ShapedType::isDynamic(), mlir::ShapedType::isDynamicStrideOrOffset(), mlir::UnrankedMemRefDescriptor::memRefDescPtr(), nDVectorIterate(), mlir::StandardTypes::None, oneToOneRewrite(), mlir::LLVMTypeConverter::packFunctionResults(), mlir::LLVMTypeConverter::promoteMemRefDescriptors(), mlir::LLVMTypeConverter::promoteOneMemRefDescriptor(), mlir::UnrankedMemRefDescriptor::rank(), mlir::ConversionPatternRewriter::replaceOp(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::Operation::result_type_begin(), mlir::StructBuilder::structType, mlir::succeeded(), mlir::success(), mlir::ComplexStructBuilder::undef(), mlir::MemRefDescriptor::undef(), and mlir::UnrankedMemRefDescriptor::undef().
Referenced by mlir::VectorConvertToLLVMPattern< SourceOp, TargetOp >::matchAndRewrite().