MLIR: lib/Dialect/OpenMP/IR/OpenMPDialect.cpp File Reference
OpenMPDialect.cpp File Reference
#include "mlir/Dialect/OpenMP/OpenMPDialect.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/OperationSupport.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include <cstddef>
#include "mlir/Dialect/OpenMP/OpenMPOpsEnums.cpp.inc"
#include "mlir/Dialect/OpenMP/OpenMPOps.cpp.inc"
Namespaces
mlir
mlir::omp
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static ParseResult parseOperandAndTypeList (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::OperandType > &operands, SmallVectorImpl< Type > &types)
Parse a list of operands with types.
static void printParallelOp (OpAsmPrinter &p, ParallelOp op)
static ParseResult allowedOnce (OpAsmParser &parser, llvm::StringRef clause, llvm::StringRef operation)
Emit an error if the same clause is present more than once on an operation.
static ParseResult parseParallelOp (OpAsmParser &parser, OperationState &result)
Parses a parallel operation.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 278 of file OpenMPDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
allowedOnce()
static ParseResult allowedOnce (OpAsmParser & parser, llvm::StringRef clause, llvm::StringRef operation) static
Emit an error if the same clause is present more than once on an operation.
Definition at line 103 of file OpenMPDialect.cpp.
References mlir::OpAsmParser::emitError(), and mlir::OpAsmParser::getNameLoc().
Referenced by parseParallelOp().
parseOperandAndTypeList()
static ParseResult parseOperandAndTypeList (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::OperandType > & operands, SmallVectorImpl< Type > & types) static
Parse a list of operands with types.
operand-and-type-list ::= (ssa-id-and-type-list) ssa-id-and-type-list ::= ssa-id-and-type | ssa-id-and-type ',' ssa-id-and-type-list ssa-id-and-type ::= ssa-id : type
Definition at line 48 of file OpenMPDialect.cpp.
References mlir::failure(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseRParen(), mlir::succeeded(), and mlir::success().
Referenced by parseParallelOp().
parseParallelOp()
static ParseResult parseParallelOp (OpAsmParser & parser, OperationState & result) static
Parses a parallel operation.
operation ::= omp.parallel clause-list clause-list ::= clause | clause clause-list clause ::= if | numThreads | private | firstprivate | shared | copyin | default | procBind if ::= if (ssa-id) numThreads ::= num_threads (ssa-id-and-type) private ::= private operand-and-type-list firstprivate ::= firstprivate operand-and-type-list shared ::= shared operand-and-type-list copyin ::= copyin operand-and-type-list default ::= default ((private | firstprivate | shared | none) procBind ::= proc_bind ((master | close | spread))
Note that each clause can only appear once in the clase-list.
Definition at line 126 of file OpenMPDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), allowedOnce(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI1Type(), mlir::Builder::getI32VectorAttr(), mlir::OpAsmParser::getNameLoc(), mlir::Builder::getStringAttr(), mlir::OperationName::getStringRef(), mlir::OperationState::name, mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), parseOperandAndTypeList(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::succeeded(), and mlir::success().
printParallelOp()
static void printParallelOp (OpAsmPrinter & p, ParallelOp op) static
Definition at line 69 of file OpenMPDialect.cpp.
References mlir::OpAsmPrinter::printRegion().