MLIR: lib/Dialect/LLVMIR/IR/ROCDLDialect.cpp File Reference
ROCDLDialect.cpp File Reference
#include "mlir/Dialect/LLVMIR/ROCDLDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/StandardTypes.h"
#include "llvm/AsmParser/Parser.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/SourceMgr.h"
#include "mlir/Dialect/LLVMIR/ROCDLOps.cpp.inc"
Namespaces
mlir
mlir::ROCDL
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static LLVM::LLVMDialect * getLlvmDialect (OpAsmParser &parser)
static ParseResult parseROCDLMubufLoadOp (OpAsmParser &parser, OperationState &result)
static ParseResult parseROCDLMubufStoreOp (OpAsmParser &parser, OperationState &result)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 100 of file ROCDLDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
getLlvmDialect()
static LLVM::LLVMDialect* getLlvmDialect (OpAsmParser & parser) static
Definition at line 37 of file ROCDLDialect.cpp.
References mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), and mlir::MLIRContext::getRegisteredDialect().
Referenced by parseROCDLMubufLoadOp(), and parseROCDLMubufStoreOp().
parseROCDLMubufLoadOp()
static ParseResult parseROCDLMubufLoadOp (OpAsmParser & parser, OperationState & result) static
Definition at line 46 of file ROCDLDialect.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::failure(), mlir::LLVM::LLVMType::getInt1Ty(), mlir::LLVM::LLVMType::getInt32Ty(), getLlvmDialect(), mlir::OpAsmParser::getNameLoc(), mlir::LLVM::LLVMType::getVectorTy(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
parseROCDLMubufStoreOp()
static ParseResult parseROCDLMubufStoreOp (OpAsmParser & parser, OperationState & result) static
Definition at line 65 of file ROCDLDialect.cpp.
References mlir::failure(), mlir::LLVM::LLVMType::getInt1Ty(), mlir::LLVM::LLVMType::getInt32Ty(), getLlvmDialect(), mlir::OpAsmParser::getNameLoc(), mlir::LLVM::LLVMType::getVectorTy(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::resolveOperands(), and mlir::success().