MLIR: lib/Dialect/Shape/IR/Shape.cpp File Reference
Shape.cpp File Reference
#include "mlir/Dialect/Shape/IR/Shape.h"
#include "mlir/Dialect/Traits.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/StandardTypes.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Support/raw_ostream.h"
#include "ShapeCanonicalization.inc"
#include "mlir/Dialect/Shape/IR/ShapeOps.cpp.inc"
Namespaces
mlir
mlir::shape
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static ParseResult parseAssumingOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, AssumingOp op)
static LogicalResult verify (AssumingAllOp op)
static void print (OpAsmPrinter &p, ConstShapeOp &op)
static ParseResult parseConstShapeOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (YieldOp op)
static LogicalResult verify (ReduceOp op)
static ParseResult parseReduceOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ReduceOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 623 of file Shape.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
parseAssumingOp()
static ParseResult parseAssumingOp (OpAsmParser & parser, OperationState & result) static
Definition at line 120 of file Shape.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::OperationState::location, mlir::OperationState::operands, mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalArrowTypeList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), mlir::OperationState::regions, mlir::OpAsmParser::resolveOperand(), mlir::success(), and mlir::OperationState::types.
parseConstShapeOp()
static ParseResult parseConstShapeOp (OpAsmParser & parser, OperationState & result) static
Definition at line 281 of file Shape.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::Attribute::cast(), mlir::OpBuilder::create(), mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast(), mlir::failure(), mlir::BoolAttr::get(), mlir::OpTrait::util::getBroadcastedShape(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::Builder::getIndexAttr(), mlir::Builder::getIndexTensorAttr(), mlir::IntegerAttr::getInt(), mlir::OwningRewritePatternList::insert(), mlir::OperationState::location, mlir::StandardTypes::None, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::success(), and mlir::OperationState::types.
parseReduceOp()
static ParseResult parseReduceOp (OpAsmParser & parser, OperationState & result) static
Definition at line 583 of file Shape.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::Paren, mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalArrowTypeList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::success(), and mlir::OperationState::types.
print() [1/3]
static void print (OpAsmPrinter & p, AssumingOp op) static
Definition at line 147 of file Shape.cpp.
References mlir::Block::back(), mlir::Attribute::cast(), mlir::PatternRewriter::eraseOp(), mlir::failure(), mlir::BoolAttr::get(), mlir::OpBuilder::getInsertionBlock(), mlir::OpBuilder::getInsertionPoint(), mlir::BoolAttr::getValue(), mlir::PatternRewriter::inlineRegionBefore(), mlir::OwningRewritePatternList::insert(), mlir::PatternRewriter::mergeBlocks(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), mlir::PatternRewriter::replaceOp(), mlir::PatternRewriter::splitBlock(), and mlir::success().
print() [2/3]
static void print (OpAsmPrinter & p, ConstShapeOp & op) static
Definition at line 272 of file Shape.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [3/3]
static void print (OpAsmPrinter & p, ReduceOp op) static
Definition at line 612 of file Shape.cpp.
References mlir::OpAsmPrinter::printOptionalArrowTypeList(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
verify() [1/3]
static LogicalResult verify (AssumingAllOp op) static
Definition at line 222 of file Shape.cpp.
References mlir::OpTrait::util::getBroadcastedShape(), mlir::Builder::getIndexTensorAttr(), and mlir::success().
verify() [2/3]
static LogicalResult verify (YieldOp op) static
Definition at line 481 of file Shape.cpp.
References mlir::Block::addArgument(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::failure(), mlir::Region::front(), mlir::RankedTensorType::get(), mlir::DenseIntElementsAttr::get(), mlir::Builder::getContext(), mlir::Builder::getIndexTensorAttr(), mlir::Builder::getIndexType(), mlir::ValueRange::getTypes(), mlir::Region::push_back(), and mlir::success().
verify() [3/3]
static LogicalResult verify (ReduceOp op) static
Definition at line 558 of file Shape.cpp.
References mlir::Operation::emitOpError(), mlir::detail::enumerate(), mlir::Block::front(), mlir::IndexType::get(), mlir::Block::getArgument(), mlir::Block::getNumArguments(), mlir::BlockArgument::getType(), and mlir::success().