MLIR: lib/Interfaces/SideEffectInterfaces.cpp File Reference
SideEffectInterfaces.cpp File Reference
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Interfaces/SideEffectInterfaces.cpp.inc"
Functions
static bool wouldOpBeTriviallyDeadImpl (Operation *rootOp)
Internal implementation of mlir::wouldOpBeTriviallyDead that also considers terminator operations as dead if they have no side effects.
Function Documentation
wouldOpBeTriviallyDeadImpl()
static bool wouldOpBeTriviallyDeadImpl (Operation * rootOp) static
Internal implementation of mlir::wouldOpBeTriviallyDead that also considers terminator operations as dead if they have no side effects.
This allows for marking region operations as trivially dead without always being conservative of terminators.
Definition at line 41 of file SideEffectInterfaces.cpp.
References mlir::Value::getDefiningOp(), mlir::SideEffects::EffectInstance< EffectT >::getEffect(), mlir::Operation::getRegions(), mlir::SideEffects::EffectInstance< EffectT >::getValue(), and mlir::Operation::hasTrait().
Referenced by mlir::wouldOpBeTriviallyDead().