MLIR: mlir::detail::IntegerTypeStorage Struct Reference
mlir::detail::IntegerTypeStorage Struct Reference
Integer Type Storage and Uniquing.
#include "IR/TypeDetail.h"
Classes
struct KeyBits
Public Types
using KeyTy = std::pair< unsigned, IntegerType::SignednessSemantics >
The hash key used for uniquing.
Public Member Functions
IntegerTypeStorage (unsigned width, IntegerType::SignednessSemantics signedness)
bool operator== (const KeyTy &key) const
unsigned getWidth ()
IntegerType::SignednessSemantics getSignedness ()
Public Member Functions inherited from mlir::TypeStorage
Dialect & getDialect ()
Get the dialect that this type is registered to.
unsigned getSubclassData () const
Get the subclass data.
void setSubclassData (unsigned val)
Set the subclass data.
Public Member Functions inherited from mlir::StorageUniquer::BaseStorage
unsigned getKind () const
Get the kind classification of this storage.
Static Public Member Functions
static llvm::hash_code hashKey (const KeyTy &key)
static IntegerTypeStorage * construct (TypeStorageAllocator &allocator, KeyTy key)
static unsigned packKeyBits (unsigned width, IntegerType::SignednessSemantics signedness)
Pack the given width and signedness as a key.
static KeyBits unpackKeyBits (unsigned bits)
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage (unsigned subclassData=0)
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()
Detailed Description
Integer Type Storage and Uniquing.
Definition at line 54 of file TypeDetail.h.
Member Typedef Documentation
KeyTy
using mlir::detail::IntegerTypeStorage::KeyTy = std::pair<unsigned, IntegerType::SignednessSemantics>
The hash key used for uniquing.
Definition at line 60 of file TypeDetail.h.
Constructor & Destructor Documentation
IntegerTypeStorage()
mlir::detail::IntegerTypeStorage::IntegerTypeStorage (unsigned width, IntegerType::SignednessSemantics signedness) inline
Definition at line 55 of file TypeDetail.h.
Member Function Documentation
construct()
static IntegerTypeStorage* mlir::detail::IntegerTypeStorage::construct (TypeStorageAllocator & allocator, KeyTy key) inline static
Definition at line 70 of file TypeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate().
getSignedness()
IntegerType::SignednessSemantics mlir::detail::IntegerTypeStorage::getSignedness () inline
Definition at line 94 of file TypeDetail.h.
References mlir::TypeStorage::getSubclassData().
getWidth()
unsigned mlir::detail::IntegerTypeStorage::getWidth () inline
Definition at line 92 of file TypeDetail.h.
References mlir::TypeStorage::getSubclassData().
hashKey()
static llvm::hash_code mlir::detail::IntegerTypeStorage::hashKey (const KeyTy & key) inline static
Definition at line 62 of file TypeDetail.h.
References mlir::spirv::hash_value().
operator==()
bool mlir::detail::IntegerTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 66 of file TypeDetail.h.
References mlir::TypeStorage::getSubclassData().
packKeyBits()
static unsigned mlir::detail::IntegerTypeStorage::packKeyBits (unsigned width, IntegerType::SignednessSemantics signedness) inline static
Pack the given width and signedness as a key.
Definition at line 82 of file TypeDetail.h.
unpackKeyBits()
static KeyBits mlir::detail::IntegerTypeStorage::unpackKeyBits (unsigned bits) inline static
Definition at line 88 of file TypeDetail.h.
The documentation for this struct was generated from the following file:
lib/IR/TypeDetail.h