MLIR: mlir::vector::VectorTransformsOptions Struct Reference
mlir::vector::VectorTransformsOptions Struct Reference
Structure to control the behavior of vector transform patterns.
#include "mlir/Dialect/Vector/VectorOps.h"
Public Member Functions
VectorTransformsOptions & setVectorTransformsOptions (VectorContractLowering opt)
Public Attributes
VectorContractLowering vectorContractLowering = VectorContractLowering::FMA
VectorTransposeLowering vectorTransposeLowering
Detailed Description
Structure to control the behavior of vector transform patterns.
Definition at line 65 of file VectorOps.h.
Member Function Documentation
setVectorTransformsOptions()
VectorTransformsOptions& mlir::vector::VectorTransformsOptions::setVectorTransformsOptions (VectorContractLowering opt) inline
Definition at line 70 of file VectorOps.h.
References mlir::vector::getVectorSubscriptAttr(), mlir::vector::getVectorSubscriptType(), and mlir::vector::populateVectorContractLoweringPatterns().
Member Data Documentation
vectorContractLowering
VectorContractLowering mlir::vector::VectorTransformsOptions::vectorContractLowering = VectorContractLowering::FMA
Definition at line 66 of file VectorOps.h.
vectorTransposeLowering
VectorTransposeLowering mlir::vector::VectorTransformsOptions::vectorTransposeLowering
Initial value:
=
      VectorTransposeLowering::EltWise
Definition at line 67 of file VectorOps.h.
Referenced by isIdentitySuffix().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Vector/VectorOps.h