MLIR: mlir::OperationState Struct Reference
mlir::OperationState Struct Reference
This represents an operation in an abstracted form, suitable for use with the builder APIs.
#include "mlir/IR/OperationSupport.h"
Public Member Functions
OperationState (Location location, StringRef name)
OperationState (Location location, OperationName name)
OperationState (Location location, StringRef name, ValueRange operands, ArrayRef< Type > types, ArrayRef< NamedAttribute > attributes, ArrayRef< Block *> successors={}, MutableArrayRef< std::unique_ptr< Region >> regions={})
void addOperands (ValueRange newOperands)
void addTypes (ArrayRef< Type > newTypes)
template<typename RangeT >
std::enable_if_t<!std::is_convertible< RangeT, ArrayRef< Type > >::value > addTypes (RangeT &&newTypes)
void addAttribute (StringRef name, Attribute attr)
Add an attribute with the specified name.
void addAttribute (Identifier name, Attribute attr)
Add an attribute with the specified name.
void addAttributes (ArrayRef< NamedAttribute > newAttributes)
Add an array of named attributes.
void addSuccessors (ArrayRef< Block *> newSuccessors)
Add an array of successors.
void addSuccessors (Block *successor)
void addSuccessors (SuccessorRange newSuccessors)
Region * addRegion ()
Create a region that should be attached to the operation.
void addRegion (std::unique_ptr< Region > &&region)
Take a region that should be attached to the Operation.
MLIRContext * getContext () const
Get the context held by this operation state.
Public Attributes
Location location
OperationName name
SmallVector< Value, 4 > operands
SmallVector< Type, 4 > types
Types of the results of this operation.
NamedAttrList attributes
SmallVector< Block *, 1 > successors
Successors of this operation and their respective operands.
SmallVector< std::unique_ptr< Region >, 1 > regions
Regions that the op will hold.
Detailed Description
This represents an operation in an abstracted form, suitable for use with the builder APIs.
This object is a large and heavy weight object meant to be used as a temporary object on the stack. It is generally unwise to put this in a collection.
Definition at line 355 of file OperationSupport.h.
Constructor & Destructor Documentation
OperationState() [1/3]
OperationState::OperationState (Location location, StringRef name)
Definition at line 165 of file OperationSupport.cpp.
OperationState() [2/3]
OperationState::OperationState (Location location, OperationName name)
Definition at line 168 of file OperationSupport.cpp.
OperationState() [3/3]
OperationState::OperationState (Location location, StringRef name, ValueRange operands, ArrayRef< Type > types, ArrayRef< NamedAttribute > attributes, ArrayRef< Block *> successors = {}, MutableArrayRef< std::unique_ptr< Region >> regions = {})
Definition at line 171 of file OperationSupport.cpp.
References regions.
Member Function Documentation
addAttribute() [1/2]
void mlir::OperationState::addAttribute (StringRef name, Attribute attr) inline
Add an attribute with the specified name.
Definition at line 389 of file OperationSupport.h.
References mlir::Identifier::get().
Referenced by mlir::impl::addArgAndResultAttrs(), mlir::ModuleOp::build(), mlir::FuncOp::build(), mlir::AffineDmaStartOp::build(), mlir::AffineDmaWaitOp::build(), buildCmpFOp(), buildCmpIOp(), buildNamedStructuredOpRegionAndAttributes(), computeTensorReshapeCollapsedType(), convertReassociationIndicesToMaps(), mlir::AffineDmaWaitOp::fold(), getLinkageAttrName(), inferExtractOpResultType(), inferStridedSliceOpResultType(), parseAffineForOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAtomicBinOp(), parseAtomicOrdering(), parseBound(), parseBranchConditionalOp(), parseConstShapeOp(), parseEntryPointOp(), parseEnumKeywordAttr(), parseEnumStrAttr(), parseExecutionModeOp(), parseFenceOp(), parseFuncOp(), mlir::impl::parseFunctionLikeOp(), parseGlobalOp(), parseGlobalVariableOp(), parseGPUFuncOp(), parseInvokeOp(), parseLandingpadOp(), parseLaunchOp(), parseListOfOperandsOrIntegers(), parseLLVMFuncOp(), parseLoopOp(), parseOptionalLLVMKeyword(), parseParallelOp(), parsePrefetchOp(), parseSelectionOp(), parseShuffleOp(), parseShuffleVectorOp(), parseSubViewOp(), parseTransposeOp(), parseVariableOp(), print(), and verify().
addAttribute() [2/2]
void mlir::OperationState::addAttribute (Identifier name, Attribute attr) inline
Add an attribute with the specified name.
Definition at line 394 of file OperationSupport.h.
addAttributes()
void mlir::OperationState::addAttributes (ArrayRef< NamedAttribute > newAttributes) inline
Add an array of named attributes.
Definition at line 399 of file OperationSupport.h.
Referenced by parseCallOp(), parseSubViewOp(), and verify().
addOperands()
void OperationState::addOperands (ValueRange newOperands)
Definition at line 185 of file OperationSupport.cpp.
References operands.
Referenced by mlir::AffineDmaStartOp::build(), mlir::DmaStartOp::build(), mlir::DmaWaitOp::build(), mlir::AffineDmaWaitOp::build(), mlir::impl::buildBinaryOp(), mlir::impl::buildCastOp(), buildCmpFOp(), buildCmpIOp(), mlir::scf::buildLoopNest(), mlir::scf::buildTerminatedBody(), extractShape(), mlir::AffineDmaWaitOp::fold(), getLLVMAtomicOrdering(), mlir::scf::getParallelForInductionVarOwner(), inferExtractOpResultType(), inferStridedSliceOpResultType(), parseBranchConditionalOp(), parseInvokeOp(), parseLaunchOp(), parseShuffleOp(), print(), and verify().
addRegion() [1/2]
Region * OperationState::addRegion ()
Create a region that should be attached to the operation.
These regions can be filled in immediately without waiting for Operation to be created. When it is, the region bodies will be transferred.
Definition at line 193 of file OperationSupport.cpp.
References regions.
Referenced by mlir::ModuleOp::build(), mlir::FuncOp::build(), mlir::scf::buildLoopNest(), buildNamedStructuredOpRegionAndAttributes(), mlir::scf::buildTerminatedBody(), mlir::AffineDmaWaitOp::fold(), getLinkageAttrName(), mlir::scf::getParallelForInductionVarOwner(), mlir::ModuleOp::parse(), parseAffineForOp(), parseAffineIfOp(), parseAffineParallelOp(), parseAssumingOp(), parseForOp(), parseFuncOp(), mlir::impl::parseFunctionLikeOp(), parseGenericAtomicRMWOp(), parseGenericOp(), parseGlobalOp(), parseGPUFuncOp(), parseGPUModuleOp(), parseIfOp(), parseLaunchOp(), parseLLVMFuncOp(), parseLoopOp(), parseModuleOp(), parseParallelOp(), parseReduceOp(), parseSelectionOp(), parseShuffleOp(), parseShuffleVectorOp(), print(), and verify().
addRegion() [2/2]
void OperationState::addRegion (std::unique_ptr< Region > && region)
Take a region that should be attached to the Operation.
The body of the region will be transferred when the Operation is constructed. If the region is null, a new empty region will be attached to the Operation.
Definition at line 198 of file OperationSupport.cpp.
References regions.
addSuccessors() [1/3]
void mlir::OperationState::addSuccessors (ArrayRef< Block *> newSuccessors) inline
Add an array of successors.
Definition at line 404 of file OperationSupport.h.
Referenced by parseBranchConditionalOp(), parseInvokeOp(), and mlir::detail::Parser::parseToken().
addSuccessors() [2/3]
void mlir::OperationState::addSuccessors (Block * successor) inline
Definition at line 407 of file OperationSupport.h.
addSuccessors() [3/3]
void OperationState::addSuccessors (SuccessorRange newSuccessors)
Definition at line 189 of file OperationSupport.cpp.
References successors.
addTypes() [1/2]
void mlir::OperationState::addTypes (ArrayRef< Type > newTypes) inline
Definition at line 379 of file OperationSupport.h.
Referenced by mlir::impl::buildCastOp(), mlir::scf::buildLoopNest(), mlir::scf::buildTerminatedBody(), diag(), extractShape(), getLLVMAtomicOrdering(), inferExtractOpResultType(), inferStridedSliceOpResultType(), mlir::LLVM::detail::oneToOneRewrite(), parseAccessChainOp(), parseAllocaOp(), parseAtomicCmpXchgOp(), parseAtomicRMWOp(), parseCallOp(), parseCmpOp(), parseCompositeConstructOp(), parseCompositeExtractOp(), parseCooperativeMatrixLoadNVOp(), parseExtractElementOp(), parseExtractValueOp(), parseGenericOp(), parseInsertElementOp(), parseInsertValueOp(), parseInvokeOp(), parseLandingpadOp(), parseLoadOp(), parseLogicalBinaryOp(), parseLogicalUnaryOp(), parseNamedStructuredOp(), parseSelectOp(), parseShiftOp(), parseShuffleVectorOp(), parseTensorFromElementsOp(), mlir::detail::Parser::parseToken(), parseUnaryOp(), parseVariableOp(), print(), mlir::LLVM::detail::vectorOneToOneRewrite(), and verify().
addTypes() [2/2]
template<typename RangeT > std::enable_if_t<!std::is_convertible<RangeT, ArrayRef<Type> >::value> mlir::OperationState::addTypes (RangeT && newTypes) inline
Definition at line 384 of file OperationSupport.h.
getContext()
MLIRContext* mlir::OperationState::getContext () const inline
Get the context held by this operation state.
Definition at line 421 of file OperationSupport.h.
References mlir::Attribute::getContext().
Member Data Documentation
attributes
NamedAttrList mlir::OperationState::attributes
Definition at line 361 of file OperationSupport.h.
Referenced by mlir::FuncOp::build(), mlir::Operation::create(), getLinkageAttrName(), mlir::ModuleOp::parse(), mlir::AffineDmaStartOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAffineApplyOp(), parseAffineForOp(), parseAffineIfOp(), parseAffineLoadOp(), parseAffineMinMaxOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAllocaOp(), parseAllocLikeOp(), parseAssumingOp(), parseAtomicCmpXchgOp(), parseAtomicRMWOp(), parseBound(), parseCallOp(), mlir::impl::parseCastOp(), parseCmpOp(), parseCompositeExtractOp(), parseCompositeInsertOp(), parseConstantOp(), parseConstShapeOp(), parseContractionOp(), parseEntryPointOp(), parseExecutionModeOp(), parseExtractElementOp(), parseExtractOp(), parseExtractValueOp(), parseFenceOp(), parseForOp(), parseFuncOp(), mlir::impl::parseFunctionLikeOp(), parseGenericOp(), parseGlobalOp(), parseGlobalVariableOp(), parseGPUFuncOp(), parseGPUModuleOp(), parseIfOp(), parseInsertElementOp(), parseInsertValueOp(), parseInvokeOp(), parseLaunchOp(), parseLLVMFuncOp(), parseLoadOp(), parseMemoryAccessAttributes(), parseModuleOp(), parseNamedStructuredOp(), parseNVVMShflSyncBflyOp(), parseNVVMVoteBallotOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseParallelOp(), parsePrefetchOp(), parseReduceOp(), parseReductionOp(), parseReturnOp(), parseSelectOp(), parseShuffleOp(), parseShuffleVectorOp(), parseSliceOp(), parseSpecConstantOp(), parseStoreOp(), parseSubViewOp(), parseTensorFromElementsOp(), mlir::detail::Parser::parseToken(), parseTransferReadOp(), parseTransferWriteOp(), parseTransposeOp(), parseTupleGetOp(), parseTupleOp(), parseVariableDecorations(), parseViewOp(), parseYieldOp(), print(), and verify().
location
Location mlir::OperationState::location
Definition at line 356 of file OperationSupport.h.
Referenced by mlir::ModuleOp::build(), mlir::scf::buildLoopNest(), mlir::scf::buildTerminatedBody(), mlir::Operation::create(), mlir::AffineDmaWaitOp::fold(), getElementPtrType(), mlir::scf::getParallelForInductionVarOwner(), mlir::ModuleOp::parse(), parseAccessChainOp(), parseAffineForOp(), parseAffineIfOp(), parseAffineParallelOp(), parseAssumingOp(), parseConstShapeOp(), parseForOp(), parseGPUModuleOp(), parseIfOp(), parseModuleOp(), parseParallelOp(), mlir::detail::Parser::parseToken(), print(), verify(), and verifyTransferOp().
name
OperationName mlir::OperationState::name
Definition at line 357 of file OperationSupport.h.
Referenced by mlir::Operation::create(), mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), parseParallelOp(), and mlir::detail::Parser::parseToken().
operands
SmallVector<Value, 4> mlir::OperationState::operands
Definition at line 358 of file OperationSupport.h.
Referenced by addOperands(), mlir::Operation::create(), mlir::DmaStartOp::parse(), mlir::AffineDmaStartOp::parse(), mlir::DmaWaitOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAccessChainOp(), parseAffineApplyOp(), parseAffineIfOp(), parseAffineLoadOp(), parseAffineMinMaxOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAllocaOp(), parseAllocLikeOp(), parseAssumingOp(), parseAtomicCmpXchgOp(), parseAtomicCompareExchangeWeakOp(), parseAtomicRMWOp(), parseAtomicUpdateOp(), parseBound(), parseBranchConditionalOp(), parseCallOp(), mlir::impl::parseCastOp(), parseCmpOp(), parseCompositeConstructOp(), parseCompositeExtractOp(), parseCompositeInsertOp(), parseContractionOp(), parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), parseExtractElementOp(), parseExtractOp(), parseExtractValueOp(), parseForOp(), parseGenericAtomicRMWOp(), parseGenericOp(), parseGroupNonUniformArithmeticOp(), parseIfOp(), parseInsertElementOp(), parseInsertValueOp(), parseInvokeOp(), parseLandingpadOp(), parseLaunchOp(), parseLoadOp(), parseLogicalBinaryOp(), parseLogicalUnaryOp(), parseNamedStructuredOp(), parseNVVMShflSyncBflyOp(), parseNVVMVoteBallotOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOuterProductOp(), parseParallelOp(), parsePrefetchOp(), parseReduceOp(), parseReductionOp(), parseReturnOp(), parseROCDLMubufLoadOp(), parseROCDLMubufStoreOp(), parseSelectOp(), parseShiftOp(), parseShuffleOp(), parseShuffleVectorOp(), parseSliceOp(), parseStoreOp(), parseSubViewOp(), parseTensorFromElementsOp(), mlir::detail::Parser::parseToken(), parseTransferReadOp(), parseTransferWriteOp(), parseTransposeOp(), parseTupleGetOp(), parseTupleOp(), parseUnaryOp(), parseVariableOp(), parseViewOp(), parseYieldOp(), and mlir::replaceAllMemRefUsesWith().
regions
SmallVector<std::unique_ptr<Region>, 1> mlir::OperationState::regions
Regions that the op will hold.
Definition at line 365 of file OperationSupport.h.
Referenced by addRegion(), mlir::Operation::create(), OperationState(), parseAffineIfOp(), parseAssumingOp(), parseIfOp(), and mlir::detail::Parser::parseToken().
successors
SmallVector<Block *, 1> mlir::OperationState::successors
Successors of this operation and their respective operands.
Definition at line 363 of file OperationSupport.h.
Referenced by addSuccessors(), and mlir::Operation::create().
types
SmallVector<Type, 4> mlir::OperationState::types
Types of the results of this operation.
Definition at line 360 of file OperationSupport.h.
Referenced by mlir::impl::buildBinaryOp(), buildCmpFOp(), buildCmpIOp(), mlir::Operation::create(), parseAffineApplyOp(), parseAffineLoadOp(), parseAffineMinMaxOp(), parseAffineVectorLoadOp(), parseAllocLikeOp(), parseAssumingOp(), parseAtomicCompareExchangeWeakOp(), parseAtomicUpdateOp(), mlir::impl::parseCastOp(), parseCompositeInsertOp(), parseConstantOp(), parseConstShapeOp(), parseContractionOp(), parseExtractOp(), parseForOp(), parseGenericAtomicRMWOp(), parseGroupNonUniformArithmeticOp(), parseIfOp(), parseNVVMShflSyncBflyOp(), parseNVVMVoteBallotOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOuterProductOp(), parseParallelOp(), parseReduceOp(), parseReductionOp(), parseROCDLMubufLoadOp(), parseShuffleOp(), parseSliceOp(), parseSubViewOp(), parseTransferReadOp(), parseTransposeOp(), parseTupleGetOp(), parseTupleOp(), parseViewOp(), and print().
The documentation for this struct was generated from the following files:
include/mlir/IR/OperationSupport.h
lib/IR/OperationSupport.cpp