MLIR: lib/Conversion/VectorToROCDL/VectorToROCDL.cpp File Reference
VectorToROCDL.cpp File Reference
#include "mlir/Conversion/VectorToROCDL/VectorToROCDL.h"
#include "../PassDetail.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVMPass.h"
#include "mlir/Dialect/GPU/GPUDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/ROCDLDialect.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/DialectConversion.h"
Functions
static LogicalResult replaceTransferOpWithMubuf (ConversionPatternRewriter &rewriter, ArrayRef< Value > operands, LLVMTypeConverter &typeConverter, Location loc, TransferReadOp xferOp, LLVM::LLVMType &vecTy, Value &dwordConfig, Value &vindex, Value &offsetSizeInBytes, Value &glc, Value &slc)
static LogicalResult replaceTransferOpWithMubuf (ConversionPatternRewriter &rewriter, ArrayRef< Value > operands, LLVMTypeConverter &typeConverter, Location loc, TransferWriteOp xferOp, LLVM::LLVMType &vecTy, Value &dwordConfig, Value &vindex, Value &offsetSizeInBytes, Value &glc, Value &slc)
Function Documentation
replaceTransferOpWithMubuf() [1/2]
static LogicalResult replaceTransferOpWithMubuf (ConversionPatternRewriter & rewriter, ArrayRef< Value > operands, LLVMTypeConverter & typeConverter, Location loc, TransferReadOp xferOp, LLVM::LLVMType & vecTy, Value & dwordConfig, Value & vindex, Value & offsetSizeInBytes, Value & glc, Value & slc) static
Definition at line 30 of file VectorToROCDL.cpp.
References mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
Referenced by replaceTransferOpWithMubuf().
replaceTransferOpWithMubuf() [2/2]
static LogicalResult replaceTransferOpWithMubuf (ConversionPatternRewriter & rewriter, ArrayRef< Value > operands, LLVMTypeConverter & typeConverter, Location loc, TransferWriteOp xferOp, LLVM::LLVMType & vecTy, Value & dwordConfig, Value & vindex, Value & offsetSizeInBytes, Value & glc, Value & slc) static
Definition at line 40 of file VectorToROCDL.cpp.
References mlir::PatternRewriter::create(), mlir::failure(), mlir::VectorType::get(), mlir::DenseElementsAttr::get(), mlir::Builder::getIntegerAttr(), mlir::Builder::getIntegerType(), mlir::Operation::getLoc(), mlir::MemRefType::getMemorySpace(), mlir::LLVM::LLVMType::getVectorNumElements(), mlir::LLVM::LLVMType::getVectorTy(), mlir::AffineMap::isMinorIdentity(), mlir::PatternRewriter::replaceOpWithNewOp(), replaceTransferOpWithMubuf(), and mlir::success().